GEOS-ESM/GEOSgcm

Externals.cfg
This makes `GEOSgcm` equivalent to CVS `Jason-3_0`
=> Update to GEOSgcm_App 1.0.1

README.md
The added `-develop` option to `parallel_build.csh` now requires some documentation. Add some first minimal lines for it.
=> Update README.md with develop option

Develop.cfg
This fixes the tripolar grid for development work. This will only advance MAPL in `Develop.cfg` so the "non-develop" build will still use the MAPL for v10.3.1
=> Move Develop.cfg to MAPL 1.1.6

CMakeLists.txt, Develop.cfg, Externals.cfg, src/Shared/.gitignore, src/Shared/CMakeLists.txt
This update moves `GFDL_fms` from inside `@GMAO_Shared` to being parallel to it and `@MAPL`.
Also get new montage plot fixes from @lltakacs.
I tested this both in `Release` and `Debug` mode and they are zero-diff to `Develop.cfg` runs of last night (as hopes since @tclune just moved FMS and didn't change any source).
=> Update GEOSgcm to external FMS

Develop.cfg, Externals.cfg
This is a dumb trivial fix but the CPLFCST_Etc CMake was copying its own `.git/` directory into its installation.
=> Update CPLFCST_Etc version to fix .git copy

Develop.cfg
This is to allow the MOM6 checkout. Note I've only changed the `Develop.cfg` here because MOM6 is only appearing on `develop` inside of `GEOSgcm_GridComp`. 
I think.
Right, @aerorahul ?
=> Update to ESMA_env 1.3.3

Develop.cfg, Externals.cfg, src/Shared/.gitignore, src/Shared/CMakeLists.txt
External library GSW-Fortran is required for MOM6.
This is ongoing work related to issue https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/70
Change-Id: I164d1be27fabb821986632ca332e3fb34e212b2a
=> Add GSW-Fortran to Shared libraries

Develop.cfg
This new FMS tag (still based on old CVS FMS) changes the value of the constant `KELVIN` in FMS to be equal to that of `MAPL_TICE` in MAPL. This is needed so that both MAPL and FMS have the same value so MOM doesn't go a bit nutty. Ask @zhaobin74 for more info.
That said, `KELVIN` is *never* used in FV3 at all, therefore it is zero-diff! And I have tested it so.
=> Update FMS to geos/orphan/1.0.1

Develop.cfg, src/Shared/.gitignore, src/Shared/CMakeLists.txt
This change is related to the general renaming of FMS. The external
moves from `@GFDL_fms` to `@FMS` and then renames all library references
from `GFDL_fms_rN` to `fms_rN`.
Also includes fixes to `@cmake`
=> Fixes #75. Rename GFDL_fms to fms. Update cmake

Develop.cfg
This is a small bug fix for using GNU compilers with Ninja. UMD_Etc has some Fortran code with comments that look like C block comments and it just confuses Ninja. As the C comments are in Fortran comments, I just edited the comments.
=> Update to UMD_Etc v1.0.2

Develop.cfg
A trawl through the configs showed that MAPL and FMS are slightly out of date. 
For MAPL, move to v1.1.13 which brings:
- Added CHANGELOG.md
- Check status of round robin and make sure that the nodearray is allocated
- Allow per-cell counters to be properly reset (if they are needed)
- Must create file unit on all processors (all_pes=.true.) when writing binary History output
- Bug fixes for vectors read in MAPL_CFIO
As for FMS, the update is minor, it's a workaround for building on macOS
=> Updates for Develop: MAPL & FMS

Develop.cfg, Externals.cfg
This merely moves the `basedir` for NCCS to point to the
`$SHARE/gmao_ops` build.
Zero-diff in my testing (it built which is probably the best test).
=> Update to ESMA_env v1.4.1

.circleci/config.yml
* Uses gcc 9.1.1, Open MPI 4.0.2, and Baselibs 6.0.4
* Uses `mepo` to clone
* Adds a weird linker flag to avoid a build issue
=> Fixes #106. Update CircleCI for MAPL 2.0

Develop.cfg, Externals.cfg, components.yaml
This moves GEOSgcm to tag `geos/2019.01.01` which is like NOAA version 2019.01.01 but with MAPL constants
=> Fixes #103. Updates GEOSgcm to FMS geos/2019.01.01

Develop.cfg, Externals.cfg, components.yaml
This update should allow for easy transition between SLES11 and SLES12 as the `g5_modules` in ESMA_env v2.0.1 should detect which you are on and then select the right modules.
=> Update to ESMA_env v2.0.1

.circleci/config.yml
This update uses the `gmao/geos-build-env-gcc-source:6.0.4` image which seems to do better and doesn't need the weird sed/cmake hack.
=> Update config.yml with new image

README.md, parallel_build.csh
This commit allows one to use `mepo` to checkout the model instead of
`checkout_externals`. To do so you run:
```
./parallel_build.csh -mepo
```
=> Add mepo capability to parallel_build

Develop.cfg, Externals.cfg, components.yaml
This update moves the SLES 12 setup of GEOSgcm to use Intel MPI 19.1 on SLES 12. Testing shows this to be zero-diff to runs on SLES11 as the compiler is not different
=> Update GEOSgcm to ESMA_env v2.0.2

Develop.cfg, Externals.cfg, components.yaml
MAPL v2.0.1 has fixes for tripolar grids. It is zero-diff if you don't use them, and adds back functionality lost from MAPL 1->2.
=> Move to MAPL v2.0.1

components.yaml
Change the "mepo names" for ESMA_env and ESMA_cmake. They were the only major repos whose mepo names weren't the same as their (non-@) directory names. E.g, doing this:
```
mepo commit env cmake
```
is more intuitive than:
```
mepo commit ESMA_env ESMA_cmake
```
=> Update components.yaml env and cmake aliases

components.yaml
This will allow cloning on machines without ssh keys
=> Use https url for GSW

Develop.cfg, Externals.cfg, components.yaml
update to MAPL version v2.0.4, fixes a bug causing History to crash in certain situations has exposed by coupled model.
=> Uptick to MAPL v2.0.4

Develop.cfg, Externals.cfg, components.yaml
This fixes an MPI_TAG issue occasionally encountered on SLES 12 at NCCS.
=> Update MAPL to v2.0.5

Develop.cfg, Externals.cfg, components.yaml
The [MAPL update](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.1.2) is to fix a tripolar grid issue in MAPL 2.1.0.
The ESMA_env fixes a `parallel_build.csh` issue at NAS.
=> Update to MAPL v2.1.2 and ESMA_env v2.1.2

.circleci/config.yml, .github/CODEOWNERS, Develop.cfg, Externals.cfg, components.yaml
This update fixes (in our testing) the `MPI_Finalize` but seen with Intel MPI on Haswell. Doing so requires Baselibs 6.0.12 as well (as part of the fix is in pFlogger, a base library)
=> Update to MAPL v2.1.3

Externals.cfg, components.yaml
This is all to get the `interp_restarts.x` bugfix from @bena-nasa into
GEOSgcm. FV3 GC 1.1.1 has the fix, but due to manage_externals nesting,
we need 1.8.5 as well
=> Update to GCM GC 1.8.5 and FV3 1.1.1

Develop.cfg, Externals.cfg, components.yaml
This is a minor update to ESMA_env, ESMA_cmake, and MAPL.
The ESMA_env has two updates. The first is to try and get zsh support with g5_modules. The second is an update to Baselibs 6.0.13 with the changes:
* ESMF 8.0.1
* gFTL-shared v1.0.7
* pFUnit v4.1.7
* pFlogger v1.4.2
* fArgParse v0.9.5
* yaFyaml v0.3.3
* Fixes for GCC 10
* Added patch for netcdf issue with GCC 10
* Added flag for HDF4 when using GCC 10
* Need to pass in extra flags to ESMF when using GCC 10
* Fix for detection for `--enable-dap` with netcdf
The ESMA_cmake is to get GCC 10 support which is also from ESMA_env.
The MAPL update is a fix for `Regrid_Util.x` which the model does not use directly.
=> Update ESMA_env, ESMA_cmake, and MAPL

Develop.cfg, Externals.cfg, components.yaml
This is a sister PR to https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/293 which updates the components.yaml for mom (at least) to geos/v1.0.2
Also updates the components.yaml and cfg files to MAPL 2.1.5
=> Move to mom geos/v1.0.2 and MAPL 2.1.5

Develop.cfg, Externals.cfg, components.yaml
This update changes:
* Update `master` -> `main`
* This is in the repos whose `develop` branch is actually `main`
* Update to ESMA_env v2.1.6
* Minor update to allow for capturing build modules
* ~~Update to FMS geos/2019.01.02~~
* ~~Update for JEDI compatibility~~
* Update to FVdycoreCubed_GridComp v1.1.3 and GFDL_atmos_cubed_sphere v1.1.2
* Support for non-72-level runs
ETA: I removed the FMS update as that should be tested more thoroughly with MOM, et al
=> Update repos and rename master->main

Develop.cfg, Externals.cfg, components.yaml
These are updates for JEDI integration work with Dan Holdaway. The complete fix will require a MAPL update as well, but these changes do not seem to affect GEOS GCM. Both the mom5 and FMS updates are pure CMake updates.
=> Updates for JEDI Integration

components.yaml
In order for https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/306 to pass its CI build, the fixture needs to have the mom5 updates for JEDI. Otherwise the `ecbuild_declare_project()` bits for GEOSgcm_GridComp fail. 
That said, if GEOSgcm says to use mom geos/v1.0.3 and is built against a GEOSgcm_GridComp before pulling in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/306, it is still zero-diff so this is safe.
=> Update MOM5 to geos/v1.0.3

Develop.cfg, Externals.cfg, components.yaml
These updates to the sub-repos are for JEDI CMake fixes. It is all zero-diff.
The GEOSgcm_GridComp equivalent PR is https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/313
=> Additional CMake Updates for JEDI Compatibility

Develop.cfg, Externals.cfg, components.yaml
This updates FMS in GEOSgcm to the [geos/2019.01.02+noaff](https://github.com/GEOS-ESM/FMS/releases/tag/geos%2F2019.01.02%2Bnoaff) release. This has been tested as zero-diff with AMIP, MOM5, and MOM6.
The main impetus is to allow building with newer Linux OSs like Fedora by not building the FMS affinity code that is unused in GEOS.
=> Update FMS to geos/2019.01.02+noaff

.gitignore, Develop.cfg, Externals.cfg, components.yaml
ESMA_cmake v3.0.7 has updates to allow disabling F2PY builds. This is needed on systems like containers and other OSs not easily tested by @mathomp4 and where the current f2py CMake system is not yet robust enough.
By default, F2PY is `ON` and users must take explicit action to turn it off.
=> Update to ESMA_cmake v3.0.7

Develop.cfg, Externals.cfg, components.yaml, config/GEOSgcm_GridComp.sparse, config/GMAO_Shared.sparse
The FV and ARIES dynamical cores are essentially unmaintained at this point in the GCM. This PR sparses out:
* ARIESg3_GridComp
* FVdycore_GridComp
from GEOSgcm_GridComp (they aren't checked out, so therefore aren't built). At the same time, we sparse out:
* GMAO_pilgrim
from GMAO_Shared repo as it is used by these two Gridded Components (and only these two).
Note that for now we just sparse from GCM as I am not sure if the ADAS (or pert or whatever!) still needs Pilgrim, so I'm not removing anything. I think we could be safe removing the two dynamical cores, but Pilgrim is a library that might be used in unexpected ways.
=> Sparse out Pilgrim, FV, ARIES

components.yaml
This zero-diff change updates FV3 GC to v1.2.0 which brings in the `fv3_setup` and `fv3.j` scripts. A companion to https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/319
=> Update to FV3 GC v1.2.0

.circleci/config.yml
This will move GEOSgcm CI to use xlarge resources. 8 vCPUs vs 2 vCPUs.
=> Move to use xlarge resource class

.circleci/config.yml
This updates the GEOSgcm CI image to use Ubuntu 10 and GCC 10
=> Use Ubuntu20 GCC10 image

Develop.cfg, Externals.cfg, components.yaml
This PR updates GMAO_Shared to v1.1.8. [This release](https://github.com/GEOS-ESM/GMAO_Shared/releases/tag/v1.1.8) was to allow Intel 19 to use CICE. Zero-diff.
=> Update to GMAO_Shared v1.1.8

components.yaml
This moves GEOSgcm_GridComp to use [FVdycoreCubed_GridComp v1.2.3](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/releases/tag/v1.2.3) which is a zero-diff update that only affects the `fv3.j` and `fv3_setup` scripts used to run the FV3 Standalone.
=> Update to FVdycoreCubed_Gridcomp v1.2.3

Develop.cfg, Externals.cfg, components.yaml
This PR updates FMS to use `geos/2019.01.02+noaff.1`. This update adds `-no-heap-arrays` when compiling with Intel. Turns out this was how it was done in CVS time, but in the transition to Git it was lost. It apparently didn't matter until we started looking at moving to Intel 19.1. 
Running MOM5 and MOM6 with `Debug` only works with this flag (or no heap-arrays at all, see https://github.com/NOAA-GFDL/MOM6/issues/1177). 
I've done a bit of testing with GEOS and found no issues, but I'll do a comprehensive test suite to make sure. For now I'll block with a label.
=> Update to FMS geos/2019.01.02+noaff.1

components.yaml
This is a companion PR to https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/339 from @sanAkel for `components.yaml`. 
I'll defer to him as to whether this is 0-diff or not as https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/339 does not have a label either. Also, I'm not sure if updating to MOM6 1.1.0 will cause a failure without the changes in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/339. I don't see any big interface changes, but it's a complex PR!
=> Update MOM6 to v1.1.0

components.yaml
This is a zero-diff update:
1. Update scripting for the FV3 Standalone (IOSERVER)
2. Pull in ntracers > 11 fix from @tclune
=> Update FVdycoreCubed_GridComp to v1.2.5

.circleci/config.yml
This uses the new 6.0.16 image that was needed for the GOCART repo
=> Update the CircleCI image

Develop.cfg, Externals.cfg, components.yaml
These are updates to allow GEOS to work on non-Intel systems. But on a machine with MKL, they are zero-diff.
=> Update to ESMA_cmake 3.2.0 and NCEP_Shared 1.0.1

Develop.cfg, Externals.cfg, components.yaml
This PR moves GEOSgcm to use ESMA_env v3.0.0 which moves to Intel 19.1.2. For more information, see the [Release Notes for ESMA_env v3.0.0](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v3.0.0).
=> Move to use Intel 19.1.2

Develop.cfg, Externals.cfg, components.yaml
This is a pretty minor update to ESMA_cmake. It has to do with handling of subdirectories where no library is built, but modules are compiled. It's more important for future ADAS integration.
=> Update to ESMA_cmake v3.2.1

Develop.cfg, Externals.cfg, components.yaml
This PR updates MAPL to v2.3.2.
Note: This PR should probably be taken along with https://github.com/GEOS-ESM/GEOSgcm_App/pull/171 though it is not necessary. But without https://github.com/GEOS-ESM/GEOSgcm_App/pull/171 there is a chance of duplicate log messages in GCM output (noisy but does not affect results).
=> Update MAPL to v2.3.2

.circleci/config.yml, .github/workflows/workflow.yml, README.md
Per Docker, soon there will be [limits on unauthenticated pulls](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). CircleCI recommends using contexts to authenticate. This PR adds the authentication
=> Add Docker authentication for pulls

components.yaml
This PR adds the ability for `mepo` to "see the fixture" letting `mepo status` and `mepo diff` work.
=> Update components to monitor fixture

CHANGELOG.md, CMakeLists.txt
Advance `CHANGELOG.md` to make a tagged release with mepo-fixture addition in `components.yaml`
=> Update CHANGELOG for 10.16.3 release

Develop.cfg, Externals.cfg, components.yaml
This updates GEOSgcm to use the NCEP_Shared v1.1.0 tag. Note that this tag has changes from the GEOSadas to NCEP_bufr, which is *sparsed out* in the GEOSgcm. Thus this should be simply zero-diff.
=> Update NCEP_Shared to v1.1.0

Develop.cfg, Externals.cfg, components.yaml
This is a patch update to FMS which changes all the `call flush()` in FMS to `flush()` to allow Intel Fortran on macOS to work (@tclune knows more of the details...something to do with the shared object libraries).
I have tested with AMIP, MOM5, and MOM6 and all run and seem zero-diff. But, it would good if @yvikhlya or @sanAkel can make sure nothing broke in coupled-space. (I'd be very sad if changing `flush` statements changed the model state. 😄 )
=> Update FMS: Fix for flush issue on macOS

Develop.cfg, Externals.cfg, components.yaml
Pulls in some bugfixes in MAPL since 2.3.4:
- Added an external grid and clock setter (for NUOPC).
- Fixed logic to allow proper termination of all imports except those specified
- Added fixture entry to `components.yaml` (requires mepo v1.23.0 or higher)
- Fixed integer overflow in memutils for big memory systems
- Fix bug with segment alarm when processing a monthly mean collection
=> Update to MAPL 2.3.6

parallel_build.csh
This was found by @sanAkel. The issue is that in `parallel_build.csh`, if `mepo init` and `clone` have already run, then the `-develop` flag is ignored. We don't want that, so instead we need to run `mepo develop`
=> Fix bug in parallel_build

Develop.cfg, Externals.cfg, components.yaml
This moves to use Intel 19.1.3 and Baselibs 6.0.22.
Testing has shown zero-diff in all but MOM6 (which was good, just different). As MOM6 is still not in usable scientific mode, this is not as important as non-zero-diff in GCM
=> Move to ESMA_env v3.1.0

Develop.cfg, Externals.cfg, components.yaml
This is a zero-diff update to MAPL 2.4.0 and ESMA_cmake 3.3.0. These need to be taken jointly due to backend changes to CMake and Baselibs-detection.
=> Update to MAPL 2.4.0 and ESMA_cmake 3.3.0

.circleci/config.yml, .github/workflows/workflow.yml
This is an update to the CI image to 6.0.22 baselibs to match ESMA_env v3.1.0
=> Update CI to 6.0.22

.circleci/config.yml, .github/workflows/workflow.yml, Develop.cfg, Externals.cfg, components.yaml, config/NCEP_Shared.sparse
This is the 'same' as https://github.com/GEOS-ESM/GEOSgcm/pull/224 from @weiyuan-jiang but with a renamed branch to (hopefully) allow CI to work.
This depends on https://github.com/GEOS-ESM/NCEP_Shared/pull/15 being tagged and released.
=> add NCEP_bufr to turn on BUILD_SHARED_LIBS

components.yaml
This is a nigh-trivial update that fixes the `fv3.j` script to handle GEOS shared object libraries. That's it!
=> Update FVdycoreCubed_GridComp to v1.2.7

components.yaml
This is a minor update to ESMA_cmake to help fix https://github.com/GEOS-ESM/GEOSchem_GridComp/issues/108 . @mmanyin tested with the real chemistries and I tested and it seemed zero-diff to me.
Essentially, it updates the ACG macro to make CMake happier.
=> Update to ESMA_cmake v3.3.2

components.yaml
This PR updates ESMA_env, ESMA_cmake, ecbuild, and GMAO_Shared to allow for use of `Aggressive` `CMAKE_BUILD_TYPE`. Note that to actually use this, you need `develop` of GEOSgcm_GridComp
=> Updates for aggressive compile flag support

components.yaml
This is a very minor update to the FVdycoreCubed_GridComp with zero-diff minimal changes [two lines in CubeGridPrototype.F90](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v1.2.7...v1.2.8).
=> Update to FVdycoreCubed_GridComp v1.2.8

components.yaml
This is a very trivial update to ESMA_cmake. It changes the `-extend_source` flag to be `-extend-source` for the Intel compiler. Intel 2021 prints out:
```
ifort: command line warning #10434: option '-extend_source' use with underscore is deprecated; use '-extend-source' instead
```
with every use. This has been tested with Intel 19.1.3 with no issues and zero-diff.
=> Update to ESMA_cmake v3.3.5 [skip ci]

components.yaml
This moves to FVdycoreCubed_GridComp v1.2.9 which is a bugfix when using GFDL microphysics. It is tested zero-diff when running the "usual" AGCM setup.
=> Update to FVdycoreCubed_GridComp v1.2.9

components.yaml
This updates to ESMA_env v3.1.3 which moves from Baselibs 6.0.22 to 6.0.27 which is a few minor library updates and some build system fixes:
This PR updates to Baselibs 6.0.27 which is a minor update to the current 6.0.22. The differences were mainly in the build system, though an important update is the yaFyaml for some work being done in MAPL.
- Use of ifort at NAS was broken by changes to make the GNU Make
system more robust
- HDF5 at NCCS with MPT requires an extra flag to compile
* cURL 7.74.0
* yaFyaml v0.4.2
* Fixes for GitHub Actions
* NCO 4.9.6
* Add patch for using antlr2 GitHub as it seems to have a bug. The patch
makes it match the previous tarball
* Moved to use antlr2 from https://github.com/nco/antlr2 as the download
link broke
* Disabled the Java, Python, and C# builds for …
=> Update to ESMA_env v3.1.3 [skip ci]

.github/workflows/workflow.yml
This is an attempt to not run CI if only, say, a markdown file is changed which can't affect the build anyway!
=> Don't run Github CI for unneeded changes

components.yaml
This PR updates MAPL to v2.5.0.
This will be needed for https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377.
Per the MAPL Changelog:
- Added an `ExternalGridManager`, to allow MAPL to have knowledge of external grids (for NUOPC).
- Added command line interface option `--isolate_nodes`. By default it is `.true.`
- Add stretching factors to file if applicable in cubed-sphere output via History and uptick to cube version 2.91
- Ability to register protoype (non-ESMF) regridders in NewRegridderManager
- Make the default clobber rather than no clobber in NetCDF formatter in PFIO
- Add basic check that the restart files match the application grid
- Add new `MAPL_AddChildFromDSO` module procedure for `MAPL_AddChild`
- Move MAPL_Cap, CapGridComp, and NUOPCwrapper to new directory in …
=> Update MAPL to v2.5.0

components.yaml
This is a minor update to ESMA_cmake to v3.3.6 which adds the ability to try and detect if you are on AMD or Intel chips. Mainly used for testing at NAS, but should be zero-diff. (The only way to trigger the code is to actually *be* on an AMD machine)
=> Update to ESMA_cmake v3.3.6

components.yaml
This PR will update to MAPL 2.6.0 and GMAO_Shared 1.3.8. These must be
taken together due to internal changes to MAPL that require removing
deprecated/obsoleted code in GMAO_Shared.
This is still zero-diff, though
=> Update to MAPL 2.6.0, GMAO_Shared 1.3.8, GEOSgcm_GridComp 1.11.5, GEOSgcm_App 1.3.14

components.yaml
This is a patch update to MAPL. MAPL 2.6.1 was mainly build systems outside of NASA. MAPL 2.6.2  has updates for the ongoing DSO work (see https://github.com/GEOS-ESM/GEOSgcm_App/pull/204 and https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377)
=> Update to MAPL 2.6.2

components.yaml
This update is a zero-diff change to FMS which builds it as shared object library.
=> Update to FMS geos/2019.01.02+noaff.4

components.yaml
Thanks to @mmanyin, we have a new version of Chem GridComp. [As stated in the release](https://github.com/GEOS-ESM/GEOSchem_GridComp/releases/tag/v1.4.2), it is zero-diff for "usual" chem and I did some tests at C24 and both actual and climatological GOCART runs are zero-diff. 🥳
=> Update to GEOSchem_GridComp v1.4.2

.gitignore, CMakeLists.txt
Based on lessons learned in https://github.com/GEOS-ESM/MAPL/pull/718 we can use CMake itself to ignore any build or install directories.
=> Use CMake to ignore build and install directories

components.yaml
This PR updates ESMA_cmake v3.3.7. All this does is fix flags when compiling with GNU on Graviton2 chips at AWS. It is *very* zero-diff. 😄
=> Update to ESMA_cmake v3.3.7

components.yaml, config/GOCART.sparse
This is part of a multi-repository pull request to move GOCART legacy's source code from the `GEOSchem_GridComp` repository to the `GOCART` repository. All of the GOCART code remain's untouched, aside from moving it to a slightly different directory location and accompanying cmake changes.
The related pull request is [#115](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/115#issue-578785185) in the `GEOSchem_GridComp` repository. Note that once the `GEOSchem_GridComp` PR has been accepted, the components.yaml file of this PR will need to be updated to new tag of the `GEOSchem_GridComp`.
I have tested this change by running a C12 experiment for 1 day and have found the results to be zero diff.
=> Moving GOCART legacy to be sourced from GOCART repository. 

.codebuild/buildspec.yml, .github/workflows/workflow.yml, components.yaml
This PR is really from @sanAkel and is updates needed to advance MOM6 in GEOS. It includes updates:
- FMS to `geos/2019.01.02+noaff.6` (zero-diff for AMIP and Coupled)
- MOM6 to `geos/v2.0.0` (zero-diff for Coupled)
- GEOSgcm_GridComp to *BRANCH* `feature/sanAkel/test_PR_gfdl-fms2` (see PR https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/416)
Of course, this latter one will be a *tag* of GEOSgcm_GridComp when all is well.
=> Update MOM6 to latest NOAA code

components.yaml
This PR updates the fvdycore code to geos/v1.1.4 and FVdycoreCubed_GridComp v1.2.10. 
This is a bugfixes with changes to the GEOS-specific vertical remapping code (as found by @bena-nasa) and `interp_restarts.x`. It is zero-diff as the code in question is only used (eventually) by the `regrid.pl` script. 
@bena-nasa can confirm this if he wishes.
=> Update to fvdycore v1.1.4 and FV3 GC v1.2.10

components.yaml
This is a patch update of MAPL. Keeping up to date. Zero-diff.
=> Update to MAPL 2.6.3

CMakeLists.txt
This PR will let someone do:
```
cmake .. -DFV_PRECISION=R8 ...
```
if they want to run FV at R8. Before you had to edit the `CMakeLists.txt`
=> CMake update to let FV_PRECISION be set on command line

components.yaml
This pulls in fvdycore v1.1.5 which adds an option to the CMake step where you can add:
```
cmake ... -DHYDROSTATIC=ON/OFF
```
The default is `ON` which is currently what GEOS builds FV3 as. If you choose `OFF` then the FV core is built with extra preprocessor variables, `MOIST_CAPPA` and `USE_COND`.
=> Updates for NH Build: fvdycore, ESMA_env, FV3 GC, GEOSgcm_App

components.yaml
This is needed as MAPL 2.6.4 has a bugfix for running GEOS on macOS with Intel 2021.
Minor update and zero-diff.
=> Update to MAPL 2.6.4

components.yaml
Use (latest) MOM6 as of 04/05/2021. 
It includes a bug fix from GEOS side of things for [stress halo-exchange](https://github.com/NOAA-GFDL/MOM6/pull/1356)
@sdrabenh please note: 
- This is a zero-diff change (simply because we do regression testing on _certain_ layouts only in `gcm_regress.j`).
- Of course, only impacts answers with the coupled model, and specifically MOM6 coupled model.
=> Switch to MOM6 as of Apr-05-2021

.circleci/config.yml, .github/workflows/workflow.yml
In anticipation of upcoming python commits, this turns off F2PY in CI builds.
=> Turn off F2PY in CI

.circleci/config.yml, .github/workflows/workflow.yml, components.yaml
This update moves GEOSgcm to use [ESMA_env v3.2.0](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v3.2.0). The main thrust of this is to move GEOS to use ESMF 8.1.0 which is needed for MAPL development.
All testing I have done has shown it zero-diff to GEOSgcm with ESMF 8.0.1. Tests were run from C12 to C720 as well as Replay and MOM6. @biljanaorescanin also tested GEOSldas and found it was zero-diff as well.
But [ESMF notes that there is a change some regridding could be non-zero-diff](https://github.com/esmf-org/esmf/releases/tag/ESMF_8_1_0). 
Thus why I'm not sure how to label this. I am fairly certain it's zero-diff, but perhaps this PR should be merged into GEOSgcm as a release in-and-of-itself. Just to let us be able to track back to ESMF change if needed?
=> Update to ESMA_env v3.2.0 (ESMF 8.1.0)

components.yaml
This updates ESMA_cmake to v3.3.8, fvdycore to v1.1.6, FVdycoreCubed_GridComp to v1.2.12
This adds the ability to use a new option `ESMA_USE_GFE_NAMESPACE` which defaults to `OFF`. 
If you set this to `ON`, you must then use the new GFE namespace style in CMake, e.g., `gftl` ==> `GFTL::gftl`. 
This is needed for testing and eventual move to Baselibs 6.2.0
=> Update to ESMA_cmake v3.3.9, fvdycore v1.1.6, FV3 GC v1.2.12

components.yaml
This is a zero-diff update to ESMA_env that just brings in some [extra code in `g5_modules`](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v3.2.1) that was available in the ADAS CVS tags. Seems useful and can't hurt!
=> Update to ESMA_env v3.2.1

components.yaml
This PR updates FVdycoreCubed_GridComp to [v1.2.13](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/releases/tag/v1.2.13). This is zero-diff in my testing of GEOSgcm as the update only affects the AdvCore which is (mainly) used by the CTM. Proposed by @JulesKouatchou and was [approved by @wmputman](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/108#pullrequestreview-640301725) (who does use it occasionally in fancy ways).
=> Update to FV3 GC v1.2.13

components.yaml
This updates GEOSgcm to use MAPL 2.6.6. This is zero-diff *except* for 2-moment microphysics which isn't. For some reason cleaning up some code in MAPL to do with profiling changes the 2-moment answers. Why? Our only thought at this point is some memory state issues in 2-moment?
Still, this is an important release. It has fixes for GEOSadas-to-MAPL2, updates to move to the new Baselibs, and I think GOCART2G might need it (@gmao-esherman could let us know). @tclune might know of other reasons we want MAPL 2.6.6
=> Update to MAPL 2.6.6

components.yaml
This updates the GCM to use ESMA_cmake v3.4.0. 
This is a precursor to merging in:
https://github.com/GEOS-ESM/ESMA_env/pull/56
which updates ESMA_env to use both Python2 and 3 at the same time.
It also leads to changes in three other repos:
https://github.com/GEOS-ESM/UMD_Etc/pull/19
https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/123
https://github.com/GEOS-ESM/GMAO_Shared/pull/168
For example, before with, say, GFIO we had:
```cmake
if (F2PY_FOUND)
if (precision STREQUAL "r4")
add_f2py_module(GFIO_ SOURCES GFIO_py.F90
DESTINATION lib/Python
ONLY gfioopen gfiocreate gfiodiminquire gfioinquire
gfiogetvar gfiogetvart gfioputvar gfiogetbegdatetime
gfiointerpxy gfiointerpnn gfiocoordnn gfioclose
)
add_dependencies(GFIO_ ${this})
endif ()
endif ()
```
Now one would do:
```cmake
if …
```
=> Update to ESMF_cmake v3.4.0

components.yaml
This is one of the updated repos that allow use of F2PY with ESMA_cmake v3.4.0 (which allows Python2 and 3 to be loaded at the same time).
=> Update UMD_Etc to 1.0.4

components.yaml
This updates MAPL to v2.6.7. This is zero-diff to v2.6.6 but has some updates needed for the GEOSadas move to MAPL2 as well as being necessary for using `MAPL_GetResource` in Surface (see https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/428)
=> Update MAPL to v2.6.7

components.yaml
This is an update needed for the GEOSadas-to-MAPL2 effort. Is zero-diff in testing by @sanAkel and myself
=> Update FMS to geos/2019.01.02+noaff.7

components.yaml
Add GEOS-Chem and HEMCO as external repositories. Once approved, I will submit a PR to [GEOSchem_GridComp](https://github.com/GEOS-ESM/GEOSchem_GridComp) to remove the legacy code copies of HEMCO and GEOS-Chem.
=> Add externals for GEOS-Chem and HEMCO.

components.yaml
Update to ESMA_cmake to fix an f2py bug with GNU as well as enable new CPP_DEBUG functionality
=> Updates for GEOSgcm v10.19

components.yaml
This PR fixes two things:
1. ESMA_cmake: f2py fixes for GNU
2. HEMCO: Remove some unneeded files that a `GLOB` was finding.
=> Update to ESMA_cmake v3.4.2 and HEMCO geos/v2.2.1

components.yaml
This PR updates MAPL to v2.6.8. This is a bugfix release of MAPL that fixes a few issues seen recently (including one with MAPL_Shmem seen at NCCS and NAS).
Also, I put in the update to FV3 GC. All this is is the "gitignore" PR that I've been spamming everywhere (see #298 )
=> Update MAPL to v2.6.8 and FV3 GC to 1.2.14

.gitignore, src/Applications/.gitignore, src/Components/.gitignore, src/Shared/.gitignore
Soon, `mepo` will have the ability to checkout subrepos as `repo`, `repo@`, or `@repo`. This commit updates the `.gitignore` files to support this flexibility.
=> Update gitignore for mepo update

CHANGELOG.md, CMakeLists.txt, components.yaml
Update MAPL to v2.7.0. Requires updates to GEOSgcm_App and FVdycoreCubed_Gridcomp due to [interface change](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.7.0)
Also update other repos at the same time.
=> Updates for v10.19.1

components.yaml
This updates MAPL to v2.7.1. This is a zero-diff release that mainly has fixes for UFS work with GOCART/MAPL. You can see the [Release Notes here](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.7.1)
=> Update MAPL to v2.7.1

README.md, components.yaml
This moves NCEP_Shared up the v5.29.0 tag to match with GEOSadas v5.29.0
All my tests show zero-diff as (I guess) everything GEOSgcm cares about in NCEP_Shared is okay.
=> Update to NCEP_Shared v1.2.0

.circleci/config.yml, .codebuild/buildspec.yml, .github/workflows/workflow.yml
It is not a good idea to do `mepo develop` in the fixture. Why, well, if something goes wrong in tagging, you might think all is okay but it's not because `develop` on one of the subrepos might work, but the fixed tag will not. Thus, you'd see the error in CI.
=> Update CI to be more logical

components.yaml
Testing with mepo to fix a bug in `mepo save` showed that life is easier for the mepo developer (aka me) if the order of the YAML entries is consistent. So, since others components with sparse do:
```yaml
local: ./src/Shared/@NCEP_Shared
remote: ../NCEP_Shared.git
tag: v1.1.1
sparse: ./config/NCEP_Shared.sparse
develop: main
```
where sparse is after tag and before develop, let's have GOCART do the same.
=> Minor update to GOCART components entry

README.md, components.yaml
ESMA_cmake v3.5.1 has a fix for macOS. It should have no effect on Linux as the code in question is only executed `if(APPLE)`
ESMA_cmake v3.5.2 has fixes for f2py builds (mainly for AeroApps)
=> Update ESMA_cmake to v3.5.2

README.md, components.yaml
This updates the [fvdycore](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere) version to geos/v1.1.7. This contains some bugfixes for upper-air regridding. All testing by @bena-nasa shows it to be zero-diff.
=> Update to fvdycore v1.1.7

README.md, components.yaml
This PR updates the GEOSgcm to use MAPL 2.8.0.
Note that this is *MOSTLY* zero-diff. For the MERRA2 GOCART Emissions, all testing shows it is zero-diff. But for the Ops GOCART Emissions, it is not. The results are non-zero-diff due to a bug fix in this version of MAPL on how grids are handled. This issue was first seen in MAPL 2.7.1, but that turned out to be due to a bug...which was fixed in MAPL 2.8.0. But, it is still a non-zero-diff change for Ops GOCART, just a *correct* non-zero-diff.
If you have questions, @bena-nasa can probably answer them better than I can. 😄
=> Update MAPL to 2.8.0

.codebuild/buildspec.yml, README.md, components.yaml
This PR updates the MOM5 version to [geos/5.1.0+1.2.0](https://github.com/GEOS-ESM/MOM5/releases/tag/geos%2F5.1.0%2B1.2.0). This has a real bug fix from @yvikhlya as well as a fix for Intel 2021 to remove warnings.
Labeling as zero-diff and non-zero-diff as I think it is zero-diff to the atmosphere and coupled MOM6 and *most* MOM5, but non-zero-diff for 1/4º MOM5 coupled runs.
=> Update MOM5 to geos/5.1.0+1.2.0

README.md, components.yaml
This PR updates GEOS to use MAPL 2.8.4. This is zero-diff in all our testing.
The [changes to MAPL](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.8.1) are fairly minor. The change some users might note is that the instantaneous timers are a little wider now.
ETA: Moved to use MAPL 2.8.2 which had fixes for the LDAS which had some issues with 2.8.1
ETA2:  Move to use MAPL 2.8.4 which has fixes for the GEOSctm that could affect GEOS (using a "-" with restarts in `AGCM.rc`)
=> Update MAPL to 2.8.4

CMakeLists.txt, README.md, components.yaml
This is a quite minor update. Essentially, if you build with `-DCMAKE_BUILD_TYPE=Debug`, the `f2py` bits of GEOS get noisier. It helps in figuring out why f2py is failing.
Also, there is now a `make package_source` or `make dist` command that will make a tarball of the source code from a build directory.
=> Update ESMA_cmake to v3.5.4

.github/workflows/workflow.yml, .gitignore, CMakePresets.json
This PR adds a `CMakePresets.json` file to GEOSgcm. This was similarly done in MAPL (see https://github.com/GEOS-ESM/MAPL/pull/924) and I'll recap the additions here. Note that for users this won't do much as unless they know how to use it, it's just a json file.
This is mainly for testing (by me and anyone else) who want to try out the functionality. It also adds `CMakeUserPresets.json` to the `.gitignore` per [CMake advice](https://cmake.org/cmake/help/v3.21/manual/cmake-presets.7.html#introduction).
For example, if you want to build GEOSgcm with Release, you can just do:
```console
cmake --preset Release
cmake --build --preset Release
```
and that'll do it. This is equivalent to:
```console
mkdir build-Release
cd build-Release
cmake .. -DCMAKE_BUILD_TYPE=Release …
```
=> Add CMakePresets.json file

.codebuild/buildspec.yml, README.md, components.yaml
This is a very minor update to ESMA_env that adds support for passing in `-rom` to `parallel_build.csh` at NAS.
=> Update to ESMA_env v3.3.1

README.md, components.yaml
This updates FV3 GC to 1.2.16. This is an extraordinarily minor update as all this does is [update some things for the `fv3_setup` script for the FV3 Standalone](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v1.2.15...v1.2.16).
=> Update FV3 GC to 1.2.16

.circleci/config.yml, .github/workflows/workflow.yml, CMakeLists.txt
This CI updates the Docker images to use GCC 11.2 and Baselibs 6.2.7. The latter isn't really necessary but it had build fixes. 
I also set the "the possible values of build type for cmake-gui" in our CMakeLists.txt to the ones we actually do support. It only really affects `cmake-gui` and maybe `ccmake` so it should be pretty transparent to users as even I don't really know how to do that!
=> Update CI and CMakeLists.txt

README.md, components.yaml
This updates ESMA_cmake to v3.5.5. This fixes a build error that a user found with the [GEOSldas on a non-NASA system](https://github.com/GEOS-ESM/GEOSldas/issues/443). Testing with GEOSgcm on discover showed this was zero-diff for both Intel and GNU.
=> Update ESMA_cmake to v3.5.5

.github/workflows/release-tarball.yml
This PR adds a new GitHub Action that on release, creates and uploads a tarball to GitHub. So if @sdrabenh released v11.12.13, then in a minute or so, we *should* have a `GEOSgcm-v11.12.13.COMPLETE.tar.xz` file that is completely mepo'd and everything.
=> Add release tarball uploader

CMakeLists.txt, components.yaml
This PR has three updates for Cascade Lake use at NCCS.
1. ESMA_env v3.4.0
* Updates to Intel 2021.2
* Move to Baselibs 6.2.7
* Adds some support for TOSS3 at NAS
2. ESMA_cmake v3.6.0
* Updates Intel Flags to be vectorized always (so far zero-diff)
3. GEOSgcm_App v1.5.4/v1.6.0 (to be made)
* Adds support for Cascade Lake in run scripts 
Also, update to MAPL 2.8.6 because it's the latest with some bug fixes
=> Updates needed for Cascade Lake at NCCS

components.yaml
This PR is contingent on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/448 and addresses https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/447.
=> Changed path to mom and mom6 components 

README.md, components.yaml
This PR is related to:
- update of MOM6 release: `geos/v.2.0.2` 
- https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/468
=> Update MOM6 (2021-Oct-12)

README.md, components.yaml
This PR moves GEOSgcm to use an OpenMP built FV3 Gridcomp and fvdycore:
* FVdycoreCubed_GridComp v1.3.0
* GFDL_atmos_cubed_sphere (fvdycore) geos/v1.2.0
=> Update to OpenMP FV3

README.md, components.yaml
This PR update ESMA_cmake to fix a bug in BASEDIR handling.
ETA: Moved to use v3.6.6 in ESMA_cmake and v3.5.0 in ESMA_env. This echoes #343 but I've tested this and these changes are fine.
=> Update to ESMA_cmake v3.6.6, ESMA_env 3.5.0

CMakeLists.txt, README.md, components.yaml
Closes #342 
This is an omnibus PR for allowing installation of source tarfiles. Needs updates to:
- ESMA_env (https://github.com/GEOS-ESM/ESMA_env/pull/67) → ESMA_env v3.5.0
- ESMA_cmake (https://github.com/GEOS-ESM/ESMA_cmake/pull/225) → ESMA_cmake v3.6.6
- GEOSgcm_App (https://github.com/GEOS-ESM/GEOSgcm_App/pull/262)
=> Closes #342. Enable tarfile installation

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.12.0. It is overwhelmingly zero-diff *EXCEPT* for one thing. In this release is a bugfix from @atrayano which fixes bad History behavior. A consequence of this bug fix can be seen in the Coupled Model History output as detailed here:
https://github.com/GEOS-ESM/MAPL/discussions/1093
The data is still all the same, but now what was two files is one.
~This also updates ESMA_cmake to v3.7.0 for which MAPL 2.12.0 is required. Fun!~ For unknown reasons, ESMA_cmake v3.7.0 causes weird issues for @sdrabenh on compute nodes *only*. Until this can be figured out, revert to 3.6.6. @tclune and myself will need to fix this.
NOTE: MAPL 2.11.0 also requires ESMA_env v3.5.0
=> Update to MAPL 2.12.0, ESMA_cmake v3.6.6

README.md, components.yaml
This PR updates the GEOSgcm to use ESMA_cmake v3.7.1. There was a thought of using ESMA_cmake v3.7.0 in #346 but @sdrabenh found some odd build behavior. v3.7.1 should fix that. Rather than push this on top of #346, we make a new PR.
ETA: Updated to 3.7.2 as 3.7.1 exposed a bit of a bug with f2py
=> Update to ESMA_cmake v3.7.2

README.md, components.yaml
This updates GEOSgcm to GMAO_Shared v1.4.11. This is zero-diff.
=> Update to GMAO_Shared v1.4.11

README.md, components.yaml
This PR moves GEOSgcm to use GEOSgcm_GridComp v1.12.8. This release has bugfixes for the `mk_*` (see https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/484)  program which affected `regrid.pl` as well as GEOSldas.
=> Update to GEOSgcm_GridComp v1.12.8

README.md, components.yaml
This updates GEOSgcm to use ESMA_env v3.7.0. All this update does is add a `-no-tar` option to `parallel_build.csh` if a user wants to avoid that.
=> Update to ESMA_env v3.7.0

README.md, components.yaml
This updates GEOSgcm to [MAPL 2.13.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.13.0). Zero-diff.
=> Update to MAPL 2.13.0

README.md, components.yaml
This PR updates to MAPL 2.14.0. 
In all testing this has been a zero-diff update. The main bugfix from this release is aimed at the GEOSldas.
=> Update to MAPL 2.14.0

README.md, components.yaml
Note this is a multi-repo update all of which rely on the others:
1. GFDL_atmos_cubed_sphere [geos/v1.3.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv1.3.0)
2. FVdycoreCubed_GridComp [v1.4.1](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/releases/tag/v1.4.1)
3. GMAO_Shared [v1.5.0](https://github.com/GEOS-ESM/GMAO_Shared/releases/tag/v1.5.0)
4. GEOSchem_GridComp [v1.7.0](https://github.com/GEOS-ESM/GEOSchem_GridComp/releases/tag/v1.7.0)
We also have an update to GEOSgcm_GridComp that is being added here:
1. GEOSgcm_GridComp [v1.13.0](https://github.com/GEOS-ESM/GEOSgcm_GridComp/releases/tag/v1.13.0)
=> Update to fvdycore geos/v1.3.0, FV3 GC v1.4.1, GMAO_Shared v1.5.0, GCM GC v1.13.0, Chem v1.7.0 

CHANGELOG.md, CMakeLists.txt, README.md, components.yaml
The updates are:
* GEOSgcm_GridComp [v10.14.0](https://github.com/GEOS-ESM/GEOSgcm_GridComp/releases/tag/v1.14.0)
* GEOSgcm_App [v1.6.0](https://github.com/GEOS-ESM/GEOSgcm_App/releases/tag/v1.6.0)
=> Updates for GEOSgcm v10.21.0

README.md, components.yaml
This PR updates three sub-repos to make things work better at NAS on the Rome nodes. Now that models built on Rome can run on Intel cores (and vice versa), we can generalize the setup scripts and `parallel_build.csh`. 
The three updates are:
1. ESMA_env v3.10.0 (see: https://github.com/GEOS-ESM/ESMA_env/compare/v3.8.0...v3.10.0)
2. FVdycore_GridComp v1.5.0 (see: https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v1.4.1...v1.5.0)
3. GEOSgcm_App v1.6.1 (see: https://github.com/GEOS-ESM/GEOSgcm_App/compare/v1.6.0...v1.6.1)
=> Updates for Rome nodes at NAS

README.md, components.yaml
This PR updates to MAPL 2.14.1. This release of MAPL was mainly for the LDAS, but there is no reason the GEOSgcm should not use the latest stable release of MAPL.
=> Update to MAPL 2.14.1

.circleci/config.yml
This PR does a few things for CircleCI. Soon, CircleCI will start charging for storage:
https://circleci.com/docs/2.0/persist-data/#how-to-calculate-an-approximation-of-your-monthly-costs
By *FAR* the most expensive storage we do is for the GCM run tests here. It was a noble experiment, but until I can do some cost calculations, etc., I'm going to turn off the GCM run tests and the `persist_to_workspace` bits here. 
I'm also going to try compressing the logfile artifacts as well.
=> CircleCI Cleanup

.circleci/config.yml, .editorconfig, CMakeLists.txt, README.md, components.yaml
This PR updates GEOS to use MAPL 2.15.0 and FV3 GC 1.6.0. In truth, there really isn't much here for the GCM. These releases were mainly for the GEOSctm which builds with `FV_PRECISION=R8` and @bena-nasa fixed some things to allow that. This should be zero-diff.
ETA: This PR now moves to MAPL 2.15.1. This version of MAPL is "sort of" non-zero-diff for History output. The actual fields/variables are zero-diff, but there have been changes to metadata as well as `lat` and `lon` are now 64-bit/double. So, if you use `cdo diffn` History output is identical. But if you use `nccmp` with the right options, it will see all sorts of changes and fail.
Also, add a `.editorconfig` file because I like it and it makes the files consistent (when used with an EditorConfig-aware editor).
=> Update to MAPL 2.15.1 and FV3 GC 1.6.0. Add editorconfig

CMakePresets.json, README.md, components.yaml
This PR updates:
- MAPL to [2.17.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.17.0)
- Bug fixes for GOCART2G History
- ESMA_env to [3.11.0](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v3.11.0)
- Removes support for SLES nodes at NAS which no longer exist
- ecbuild to [geos/1.1.0](https://github.com/GEOS-ESM/ecbuild/releases/tag/geos%2Fv1.1.0)
- Updates `FindNetCDF.cmake` file; zero-diff to GEOS
=> Update MAPL to 2.17.0. Update ecbuild and env

README.md, components.yaml
This PR brings in updates to ESMA_cmake and ecbuild (GEOS fork). The first adds a `FindESMF.cmake` and the second updates the `FindNetCDF.cmake` in our ecbuild.
These files are from NOAA-EMC and allow MAPL to build with Spack and GNU. 
It doesn't affect Baselibs builds of GEOS and is zero-diff in my testing.
=> Update ESMA_cmake and ecbuild

.circleci/config.yml, README.md, components.yaml, config/RRTMGP.sparse
Closes #371 
This PR will move GEOS to use RRTMGP as a fork. 
Contingent on: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/528
=> Closes #371. Add RRTMGP as a fork

README.md, components.yaml
This PR update GEOSchem_GridComp to v1.8.1. This has a bugfix for Achem (see https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/164) for running GEOSgcm with GOCART2G on GNU compilers.
=> Update Chem to 1.8.1

.github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md, .github/workflows/push-to-main.yml
MAPL will soon be working toward a version 3 that will have incompatibilities to MAPL 2. This branch is now on this repository called `release/MAPL-v3` and will allow the SI Team to make changes to this repository while not affecting `main` directly.
What this PR does is add a GitHub Action so that any push to `main` (aka, any PR merged into `main`) also automatically makes a PR from `main` into `release/MAPL-v3`.
This way, our tracking branch can "keep up" with `main` and once MAPL 3 is ready to go, all that is needed is to merge `release/MAPL-v3` into `main` and we are good.
=> GitHub Actions for MAPLv3 development

.circleci/config.yml, README.md, components.yaml
This PR updates the GCM to use:
- MAPL 2.18.3
- ESMA_cmake 3.12.0
- ESMA_env 3.13.0
This is a zero-diff update, **_BUT_** comparators like `nccmp` will show a difference in lats and lons of History output. This is due to a change because GMAO Ops found that MAPL History lats and lons were sometimes reported as, say, 6.5000000001 instead of 6.5. This was due to some extra FP math. This is now avoided, but it does mean the lats and lons are _slightly_ different.
Note that the **_data_** in the History files is exactly the same. It's only the lats and lons that are affected.
=> Update to MAPL 2.18.3, ESMA_cmake 3.12, ESMA_env 3.13

README.md, components.yaml
Closes #387 
This PR gathers up the upstream CMake changes for Spack support. It will stay draft until everything is released as a tag.
=> Fixes #387. Updates for Spack Support

components.yaml
This is a change to how the MOM6 repo is handled by mepo. Namely, the parent repo of our fork is now [mom-ocean/MOM6](https://github.com/mom-ocean/MOM6), but used to be a different repo which had a `dev/gfdl` branch. At that time, we said "Okay, let `dev/gfdl` be our development branch as well."
However, @sanAkel, in conversation with @marshallward, says that mom-ocean is the right one to fork from and since it does not have a `dev/gfdl` branch, our fork shouldn't either. In lieu of a `geos/main` or our own development branch, we might as well point our repo to `main`.
Note that @sanAkel mainly does work with the MOM6 folks directly (and any changes feed through them), so we probably won't need GEOS-specific branches on our fork unless things really diverge.
=> Change develop branch of MOM6 to main

README.md, components.yaml
This PR upticks MOM6 and GEOS_OceanGridComp.
It impacts the coupled model, and only MOM6-ocean. It is non-zero diff for the MOM6-coupled model because defaults have been updated.
=> Update MOM6 and GEOS_OceanGridComp

README.md, components.yaml
Updated the PR to move to MAPL 2.20.0. This has updates for couplers and ExtData2G.
This PR also includes updates from MAPL 2.19.2. This is a patch on 2.19.1 to fix a bug writing native cubed-sphere output with GNU.
=> Update to MAPL 2.20.0

README.md, components.yaml
This PR updates GEOSgcm to use:
* FVdycoreCubed_GridComp [v1.8.0](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/releases/tag/v1.8.0)
* fvdycore [geos/v1.4.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv1.4.0)
This updates are primarily for Spack compatibility (see #387). The Fvdycore_Cubed update also includes a change from @sdeastham that suppresses a print when using AdvCore.
These are zero-diff.
=> Update FV3 GC to 1.8.0, fvdycore to 1.4.0

README.md, components.yaml
This PR addresses https://github.com/GEOS-ESM/GOCART/issues/140 with fixes by @bena-nasa, with releases from @mmanyin and @amdasilva 
This has two updates:
* [GEOSchem_GridComp v1.9.2](https://github.com/GEOS-ESM/GEOSchem_GridComp/releases/tag/v1.9.2)
* [GOCART v2.0.7](https://github.com/GEOS-ESM/GOCART/releases/tag/v2.0.7)
I think this is all zero-diff though we will of course test.
NOTE: once this PR is in, we can take the simplify emissions PR (https://github.com/GEOS-ESM/GEOSgcm_App/pull/320). That PR relies on Chem v1.9.2 to work.
=> Update to GOCART 2.0.7, Chem 1.9.2

README.md, components.yaml
This PR updates GEOSgcm to use [MAPL 2.21.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.21.0). 
The main impetus for this PR is to quash ESMF errors found during the nightly test runs. MAPL 2.21 has a fix for History handling that makes ESMF happier. It is zero-diff in all testing as, really, nothing of vital import in MAPL itself changed, just bug fixes and some updates from @bena-nasa for PRINTSPEC use.
=> Update to MAPL 2.21.0

README.md, components.yaml
This PR updates GEOSgcm to use ESMA_cmake v3.15.1. This update mainly has updates to how finding ESMF is handed in our CMake system.
Note that this is technically required for https://github.com/GEOS-ESM/GMAO_Shared/pull/262 though you need to build the full ADAS to find that out.
=> Update to ESMA_cmake v3.15.1

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This PR updates MAPL to 2.23.0. This *REQUIRES* using ESMA_env v4.2.0 (aka Baselibs 7.5.0) due to a need for a newer yaFyaml library version. This allows for better error handling in ExtData2G. This is a zero-diff update as nothing has really changed in MAPL, save for needing a new library.
This PR also updates GEOS to use:
1. ESMA_env v4.2.0
- Moves to use Baselibs 7.5.0 (needed by MAPL 2.23.0)
2. ESMA_cmake v3.17.0
- Updates for Apple Silicon support
- Change to GNU Release flags
NOTE: That for GNU Release runs of GEOS, this will be **non-zero-diff**. The change was to better support GCC 12. But this is **zero-diff** for Intel Fortran.
=> Update to MAPL 2.23.0, ESMA_env v4.2.0, ESMA_cmake v3.17.0

README.md, components.yaml
This PR updates the FVdycoreCubed_GridComp version to v1.9.0. This was a zero-diff bug fix which was exposed in testing with GNU + Intel MPI (see https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/issues/165)
It would be non-zero-diff if you turn on the right things in FV3, but only @wmputman knows how to do that. 😄 (Something to do with Rayleigh friction...if I read the code right.)
=> Update FV3 GC to 1.9.0

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.23.1. This update mainly has a bugfix for an issue with binary History output seen in the LDAS, but which could be seen in the GCM if someone asked for Binary output as well.
=> Update to MAPL 2.23.1

README.md, components.yaml
A new QuickChem module is introduced, aimed at providing lightweight implementations of key chemical species. The project is led by B. Duncan, coordinating with A. da Silva and L. Ott. The initial species, provided in v1.0.0, is OH, based on an ML algorithm of D. Anderson .
QuickChem will be supported in an upcoming release of GEOSchem_GridComp. It will not be run by default.
This PR is zero diff.
=> Add @QuickChem under @GEOSchem_GridComp

README.md, components.yaml
This PR update GEOSchem_GridComp to v1.9.6. This is a very minor update that adds the new QuickChem repo from #439 to the `.gitignore` file to make sure git ignores the embedded repo (a la GOCART).
Here is the difference between the two versions:
https://github.com/GEOS-ESM/GEOSchem_GridComp/compare/v1.9.5...v1.9.6
=> Update to GEOSchem_GridComp v1.9.6

README.md, components.yaml
This PR updates FVdycoreCubed_GridComp to v1.10.0. This is a nigh-trivial update that adds AWS support to the FV3 standalone scripts.
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v1.9.0...v1.10.0
=> Update to FVdycoreCubed_GridComp v1.10.0

.gitignore, README.md, components.yaml
This PR updates GEOSgcm to use ESMA_cmake v3.18.0. The main update to this was adding some ignores to the CPack "generate tarfile" step where it seemed like some editor temporary files could cause issues with `parallel_build.csh`.
Also, we add the same files to the `.gitignore` because...why not.
=> Update to ESMA_cmake v3.18.0

README.md, components.yaml
This PR updates:
- [GEOS_OceanGridComp](https://github.com/GEOS-ESM/GEOS_OceanGridComp) to `v1.1.1`
- [GEOS MOM6 _fork_](https://github.com/GEOS-ESM/MOM6/) to  `geos/v2.0.4`
=> Update components.yaml for ocean model

CMakeLists.txt, README.md, components.yaml
This PR updates the compiler and MPI for GEOS to be Intel 2022.1 (aka Intel Fortran 2021.6). 
All testing shows this to be zero-diff, and ongoing development by @aoloso and @darianboggs shows that 2022.1 seems to fix some issues in their OpenMP work.
ETA: I've pushed an update to use v4.4.0 as this adds support for TOSS4 at NAS to which [its Rome nodes are moving soon](https://www.nas.nasa.gov/hecc/support/kb/news/help-us-test-rome-nodes-on-toss-4_662.html)
ETA2: I also upped the required CMake version to 3.17. This is already the case in MAPL anyway, but at least here it will fail fast rather than waiting around to get to MAPL during CMake time.
=> Update to ESMA_env 4.4.0 (Intel 2022.1, TOSS4)

README.md, components.yaml
This PR updates MAPL to 2.25.0. This is a needed upgrade for CICE loadbalancing coming in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/626
=> Update to MAPL 2.25.0

README.md, components.yaml
This PR moves GEOSgcm to use FVdycoreCubed_GridComp v1.11.0. This has two updates:
1. Fixes issues with running FV3 at double precision
2. Updates `fv3_setup` and `fv3.j` with some experimental support for Singularity.
This is zero-diff in all testing at R4. At R8, there will be some differences in FV3.
=> Update FVdycoreCubed_GridComp to v1.11.0

README.md, components.yaml
This PR updates MAPL to v2.26.0. This version contains a bugfix needed for testing with ExtData2G.
cc: @sdrabenh
=> Update to MAPL 2.26.0

.circleci/config.yml, CMakeLists.txt, README.md, components.yaml, src/Shared/CMakeLists.txt
This PR is needed for building GEOSgcm with spack-stack (see https://github.com/NOAA-EMC/spack/pull/174).
Here we update the main `CMakeLists.txt` for the case where Baselibs is not found so that all the needed `find_package()` and `add_library(ALIAS)` calls can be made. Testing shows that this is zero-diff.
I've also added a test for the `esmf_ROOT` environment variable that Spack creates and use that to find the `FindESMF.cmake` file. Not perfect, but now when building by hand you don't have to do `-DCMAKE_MODULE_PATH=${esmf_ROOT}/cmake`.
Also, this adds a smidge of the changes needed for FMS-in-spack. I can't turn this on by default due to changes that are needed in fvdycore (see https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/51). As this is an *interface* change, we have to …
=> Updates for Spack Stack

README.md, components.yaml
This PR updates GEOSgcm to use FVdycoreCubed_GridComp v1.12.1 which has a fix for some mass flux units on exports.
Note: Could change metadata in history collections, but the state is not changed.
=> Update to FVdycoreCubed_GridComp v1.12.1

README.md, components.yaml
This PR updates to MAPL 2.28. 
The main changes from 2.27.1 are:
* Changes to support component level hybrid MPI/OpenMP
* Ability to apply masks to expressions in ExtData2G
* Added a subroutine that adds all exports from a child
* Implement ISO 8601 (Date/Time) support for MAPL
As well as a fix for `AddChildFromDSO` that was affecting MAPL3 (but MAPL2 had the same bug).
The changes from 2.27.1 to 2.28 are:
> With tripolar history output, the difference is due to a better tripolar grid factory being added to this release, so that tripolar History output is more like that of other grids including adding corner lats and lons.
> 
> For *ALL* History output, there is a global metadata change due to a request from NOAA. Namely, the default `Contact:` in History Gridded Component is now set to …
=> Update to MAPL 2.28

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.29. 
This release is zero-diff and has some changes needed for work by @bena-nasa with `time_ave.x` modernization as well as work by @weiyuan-jiang with the CatchCN mk_restarts (https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/658).
=> Update to MAPL 2.29.0

README.md, components.yaml
This PR is needed to fully support the multiple GMI mechanism Chem PR from @ssteenro [now in GEOSchem_GridComp v1.10.3](https://github.com/GEOS-ESM/GEOSchem_GridComp/releases/tag/v1.10.3) (which I'm guessing @mmanyin will be making a PR for or will inform @sdrabenh to add to next release 😄 ).
The ESMA_env change adds a `-gmi_mechanism` option to `parallel_build.csh` (via `build.csh`) so users can easily change mechanisms.
I've also pushed a change to move to ESMA_cmake v3.19.0. This mainly changes the GNU debug flags as well as has a check on if `CMAKE_INSTALL_PREFIX` is writable (so you don't have to wait until the end of the build to find out, it dies quick).
=> Update ESMA_env to v4.5.0 and ESMA_cmake to v3.19.0

README.md, components.yaml
This PR updates GEOSgcm to use ESMA_env v4.6.0. This update has a new feature for `parallel_build.csh` to allow for arbitrary CMake options to be passed in. 
This is done by the use of `-- ` to trigger `parallel_build.csh` to say "everything after this is an extra CMake option". Per the updated usage:
```
extra cmake options
To pass in additional CMake options not covered by the above flags,
after all your flags, add -- and then the options. For example:
parallel_build.csh -debug -- -DSTRATCHEM_REDUCED_MECHANISM=ON -DUSE_CODATA_2018_CONSTANTS=ON
and these options will be appended to the CMake command.
NOTE: Once you use --, you cannot use any more flags. All options
after -- will be passed to CMake and if not a valid CMake option,
could cause the build to fail.
```
=> Update to ESMA_env v4.6.0

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.30.2. This release brings the new `time_ave_util.x` from @bena-nasa that can be used to time average files on more than just Lat-Lon grids. It also fixes a bug with History and ungridded dims found by @dr0cloud (see https://github.com/GEOS-ESM/MAPL/issues/1811)
Otherwise, it is pretty much identical to MAPL 2.29
=> Update to MAPL 2.30.2

README.md, components.yaml
This PR update GEOSradiation_GridComp to v1.1.0. This release is technically a non-zero-diff change to v1.0.0 but only because the the `FSWBAND` fields in the internal restart were all `MAPL_UNDEF` in v1.0.0 but now are filled (see below). All other fields are the same.
Per @dr0cloud, there are two changes:
1. Under RRTMG the exports FSWBAND[NA] were previously MAPL_UNDEF because there was no facility in RRTMG to calculate them yet. This facility is now added. Clearly no one has been using these exports, but it is good to be able to provide them. This is non-zero-diff only in the sense that FSWBAND[NA] now have realistic values for RRTMG, but zero-diff effectively, since no one was using them yet.
2. RRTMG can now provide two new Exports DROBIO and DFOBIO. These are HorzOnly exports but …
=> Update to GEOSradiation_GridComp v1.1.0

README.md, components.yaml
This PR updates GEOSgcm to use NCEP_Shared v1.2.1. This is a pretty minor update with build fixes for GNU and Intel Debug builds.
=> Update to NCEP_Shared v1.2.1

.circleci/config.yml, .docker/Dockerfile, .github/workflows/trigger-circleci-pipeline-on-release.yml, README.md, components.yaml
This PR adds GitHub Actions and CircleCI code to build a Docker image on release. This was based on tests in the gcm-container-test repo which was a fork of this.
---
Testing on discover (which still requires a bit of hand work), shows that the container isn't that much different from a native build. The columns are model throughput at days/day and are the average of 3 runs.
Resolution  |  Native    |  Container  |  Speedup
------------|------------|-------------|---------
C24         |  1120.953  |  1034.057   |  0.92
C48         |  526.617   |  508.689    |  0.97
C90         |  230.720   |  236.095    |  1.02
C180        |  141.796   |  141.228    |  1.00
C360        |  132.044   |  127.004    |  0.96
C720        |  55.737    |  52.132     |  0.94
=> Build Docker containers on Release

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.31.0. The main impetus for this PR is to introduce two new features and fixes:
1. This has a change needed for land development as seen in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/618. 
2. Updates needed to use netCDF quantize abilities. Note that this will need an update to ESMA_env and ESMA_cmake which will come in a future PR. But, for now, this support is there, just can't be enabled until a newer netCDF is used. 
In all testing, MAPL 2.31.0 is zero-diff.
=> Update to MAPL 2.31.0

README.md, components.yaml
This PR updates GEOSradiation_GridComp to v1.2.0. The main change here (per @dr0cloud) is extending the work from v1.1.0 that enabled production of OBIO surface solar downwelling direct and diffuse fluxes on OBIO bands. The previous release worked for RRTMG only. This release expands the facility to all three radiation codes.
It is activated by putting `SOLAR_TO_OBIO: .TRUE.` in `AGCM.rc` and then associating the solar export fields `DROBIO` and `DFOBIO` either by exporting them in history or adding future connectivity to the OradBioGC. It is off by default and therefore zero-diff. Even if it is on, it is effectively zero-diff ... it only potentially produces two currently unused new exports, now for RRTMGP and Chou-Suarez as well as for RRTMG (see …
=> Update to GEOSradiation_GridComp v1.2.0

README.md, components.yaml
This PR moves MAPL to 2.33.0. This release has changes from @bena-nasa for fixing the GAAS ExtData issues and from @weiyuan-jiang for a new reader for 4d integer fields. It also has fixes for ExtData2G with GNU.
All testing is zero-diff.
=> Update to MAPL 2.33.0

README.md, components.yaml
This PR updates the GEOSgcm to GMAO_Shared v1.6.3 which has a bug fix for the `remap_restarts.py` script when remapping from MERRA-2.
=> Update to GMAO_Shared v1.6.3

README.md, components.yaml
See [here](https://github.com/GEOS-ESM/GEOS_OceanGridComp/releases/tag/v1.2.1) for more details.
=> Uptick GEOS_OceanGridComp to v.2.1

.github/workflows/enforce-labels.yml
This PR uses the new ability of v3 of our label enforcer to provide for a custom message upon enforcer failure.
=> Add custom messages to label enforcers

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.34 and ESMA_cmake 3.24. The ESMA_cmake update is trivial (extra debug flags for Intel and some `ifx` trial support).
The MAPL update is substantive in one way: it will change GOCART History output. The *data* is the same, but handling of split fields has changed so for example before you had DU, DU002, DU003... but now it'll be DU001, DU002, DU003...
Also, changes were made which can affect the long name/standard name metadata for some GOCART output, see https://github.com/GEOS-ESM/GOCART/issues/202
=> Update to MAPL 2.34.0, ESMA_cmake 3.24.0

CHANGELOG.md, CMakeLists.txt, README.md, components.yaml
Closes #508 
This PR moves TR, GMI, and StratChem to separate repos. There will be a few steps to get this in:
=> Move TR, GMI, and StratChem to separate repos

.github/dependabot.yml, .github/workflows/enforce-labels.yml, .github/workflows/push-to-main.yml, .github/workflows/release-tarball.yml, .github/workflows/trigger-circleci-pipeline-on-release.yml
This PR updates various GitHub Actions. The main update is adding dependabot. As we know from MAPL, dependabot can be noisy. Hopefully not too bad, but it does make us be sure to keep up to date!
=> Update GitHub Actions

README.md, components.yaml
This PR updates GEOS to MAPL 2.35.2. This is a zero-diff update and has some changes from @weiyuan-jiang that were needed for work he's doing with the land group as well as bug fixes for ExtData from @bena-nasa and fixes for UFS folks
=> Update to MAPL 2.35.2

README.md, components.yaml
This PR updates to ESMA_cmake v3.26.0. This is mainly for use with PRs (current and future) to better handle Rome nodes at NAS and Azure (see https://github.com/GEOS-ESM/GEOSgcm_App/pull/411)
=> Update to ESMA_cmake v3.26.0

README.md, components.yaml
Per ESMF, ESMF 8.4.0 (which is in ESMA_env 4.8.0) has a [possible memory corruption bug](https://github.com/esmf-org/esmf/releases/tag/v8.4.1).
This PR moves GEOS to use ESMA_env v4.9.1 which is still zero-diff to v4.8.0. Changes since 4.8.0 are:
- Moved to Baselibs 7.8.1
- Updated
- ESMF v8.4.1
- This is a bug-fix against ESMF 8.4.1 and is a recommended update
- Moved to Baselibs 7.8.0
- curl 7.87.0
- NCO 5.1.4
- CDO 2.1.1
- NOTE: CDO now requires C++17 so this means if you are building with Intel C++ (Classic), you should use GCC 11.1 or higher as the backing GCC compiler [per the Intel docs](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/language-options/std-qstd.html)
- Move to use GCC 11 …
=> Update to Baselibs 7.8.1 (ESMF 8.4.1)

.circleci/config.yml, README.md, components.yaml
This PR updates to ESMA_cmake v3.28.0. This has updates for Python detection needed for MAPL `develop` (mea culpa) and pyobs work by @patricia-nasa
=> Update to ESMA_cmake v3.28.0

.circleci/config.yml, README.md, components.yaml
This PR is to collect changes to `components.yaml` for stretched grid support and more.
So far:
* FVdycoreCubed_GridComp v2.0.0 → v2.2.0 (stretched grid support, add'l helicity diagnostics)
* GFDL_atmos_cubed_sphere geos/v2.0.0 → geos/v2.2.0 (stretched grid support, add'l helicity diagnostics)
* MAPL v2.35.2 → v2.36.0 (bug fix for an ExtData2G, support for XY grid factory for Lambert output)
* GEOSradiation_GridComp sdr_v1.2.0.1 → v1.3.0 (no real change, just a v-tag)
=> Updates for stretched grid and more

README.md, components.yaml
Update GEOSgcm to use:
* GEOS_Util v1.1.1
* FVdycoreCubed_GridComp v2.2.1
This fixes bugs in `remap_restart.py` and `interp_restarts.x`
=> Bug fixes for remapping restarts

README.md, components.yaml
This PR updates to GOCART `sdr_v2.1.2.2`. This is non-zero-diff due to [changes in 1moment handling](https://github.com/GEOS-ESM/GOCART/commit/f4c7da3a2b1cedced27011dd66a7ef854c674630).
Note: To use GOCART2G data-driven, you'll want to update to GEOSgcm_App `develop` until GEOSgcm_App is tagged.
=> Update to GOCART sdr_v2.1.2.2

README.md, components.yaml
This PR updates:
* GEOS_OceanGridComp v2.0.0 → v2.1.0
* MOM6 geos/v2.1.0 → geos/v2.2.0
* MITgcm checkpoint67q → checkpoint68o
@amolod @atrayano Can you confirm/double-check I got the right MITgcm version? I think it's what @atrayano told me this morning, but...
I'm marking 0-diff only in that I'm sure it's 0-diff for the *atmosphere*. Not sure about coupled (MOM6 or MITgcm).
=> Update Ocean GC, MOM6, MITgcm versions

README.md, components.yaml
This PR has bugfixes for ESMA_env (build.csh at NAS) and GEOSgcm_GridComp (bug in binary restart reads).
It also has an update to [FVdycoreCubed_GridComp v2.4.0](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/releases/tag/v2.4.0) which is trivially zero-diff as it adds code that isn't really compiled. But it might be good for @pchakraborty 's work with GPUs to get this in a tag.
=> Bugfixes for build.csh and Moist Binary reads

README.md, components.yaml
This PR updates GEOSgcm to FVdycoreCubed_GridComp v2.4.3. 
This has a *bugfix* to the FV3 Standalone along other more small trivial updates to FV3 GC for the FV3 standalone which [suppresses some prints](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/224) running in the standalone mode and adds pFlogger support.
ETA: Update to 2.4.3 which has support for a `--site` flag in `fv3_setup`
The GCM is not affected by this, but since we build the standalone with the GCM, might as well get the fixes in here too and not just in GEOSfvdycore.
=> Update to FVdycoreCubed_GridComp 2.4.3

README.md, components.yaml
This PR updates GEOSgcm to use GEOS_OceanGridComp v2.1.1. This is a zero-diff update to AMIP and MOM6 coupled runs. But it does have a bug fix for MITgcm runs.
This also updates GMAO_Shared to v1.9.1 which has updates for CICE4: build as shared library and another fix for MITgcm
Tested both together and they are zero-diff for AMIP and MOM6
=> Update to GEOS_OceanGridComp v2.1.1, GMAO_Shared v1.9.1

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.39.3. This has a bug fix when performing vertical regridding in History when the output grid cannot be decomposed so that every core has a DE. (Mainly exposed by very-high-resolution runs)
=> Update to MAPL 2.39.3

README.md, components.yaml
This PR updates to FVdycoreCubed_GridComp v2.5.0. Changes include:
* Changes to make singularity runs simpler
* Clean up use of global memory in interp_restarts.x
* Separate init and finalize in geos-gtfv3
=> Update FVdycoreCubed_GridComp to v2.5.0

.circleci/config.yml, README.md, components.yaml
This PR updates GEOS to use MAPL 2.39.4 and ESMA_cmake v3.30.0.
The MAPL update is the important one as it has a fix for an ExtData2G Climatology bug encountered by @christophkeller under rare circumstances (see https://github.com/GEOS-ESM/MAPL/issues/2192).
The ESMA_cmake update adds a `QUIET_DEBUG` option to make compiling of GEOS a bit quieter (useful for CI/container work being undertaken). This option is default off and only affects Intel Fortran.
=> Update to MAPL 2.39.4, ESMA_cmake 3.30.0

README.md, components.yaml
This PR updates to MAPL 2.39.5. This update has a bug fix for HISTORY when a user would specify an alias in HISTORY.rc for a variable with a single bin/ungridded dimension and the alias would be wrongly ignored. 
So before this:
```
'CA.brEXTTAU'    , 'CA.br'     , 'BREXTTAU'    ,
```
would lead to output of `CA.brEXTTAU001` instead of `BREXTTAU` or `BREXTTAU001`.
In MAPL 2.39.5, this will now result in a variable called `BREXTTAU` *without* the `001`. If a user desires that name, they can update the alias in HISTORY.
Beyond that fix, this is zero-diff to MAPL 2.39.4 (all other HISTORY and the state is the same)
=> Update to MAPL 2.39.5

README.md, components.yaml
This PR updating ESMA_env to v4.18.0 removes the ability to select Haswell when running `parallel_build.csh` at NCCS. It also adds a new "any" option that will build on either a Skylake or Cascade Lake...but only for Intel builds. GNU builds at NCCS use Open MPI and must build (and run) on Cascade Lake.
This is a sort of companion to https://github.com/GEOS-ESM/GEOSgcm_App/pull/489 which does something similar to the setup scripts.
=> Updates to remove Haswell at NCCS (build.csh)

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.39.7. This has two patches on top of 2.39.5:
> ## [2.39.7] - 2023-07-18
> 
> ### Fixed
> 
> - Fix a bug so that MultigroupServer does not allow a file written by multiple processes at the same time.
> 
> ## [2.39.6] - 2023-07-18
> 
> ### Changed
> 
> - Relaxed restriction in the tripolar grid factory so that grids can be made even when the decomposition deos not evenly divide the grid dimension so that the factory can be used in utilities where the core count makes such a condition impossible to satisfiy
> 
> ### Fixed
> 
> - Fix a bug in `time_ave_util.x` so that it can work with files with no vertical coordinate
> 
All testing shows it zero-diff.
=> Update to MAPL 2.39.7

README.md, components.yaml
This PR updates ESMA_cmake to v3.31.0. This is extraordinarily minor as all it does is suppress some warnings if you are building with Intel Debug. The log files were filled with some useless (to most/all users) warnings and this just removes them.
=> Update to ESMA_cmake v3.31.0

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This PR updates GEOS to use Baselibs 7.14.0 (aka ESMA_env v4.19.0). This is needed for MAPL 2.40 (soon to come) but the *current* model shouldn't care as it uses MAPL 2.39 and it is zero-diff.
The updates are:
- ESMF v8.5.0
- GFE v1.11.0
- gFTL-shared v1.6.1
- pFUnit v4.7.3
- curl 8.2.1
- NCO 5.1.7
- CDO 2.2.1
=> Update to Baselibs 7.14.0

CHANGELOG.md, CMakeLists.txt, README.md, components.yaml
This PR updates GEOS to MAPL 2.40. Due to #625, we now require this. Mea culpa. All tests show it to be zero-diff to MAPL 2.39
We also update to GEOSgcm_App v2.2.1 and GEOSgcm_GridComp v2.1.4
=> Update to MAPL 2.40, GEOSgcm_App v2.2.1, GEOSgcm_GridComp v2.1.4

README.md, components.yaml
This updates GEOSgcm to use ESMA_cmake v3.31.1 and MAPL 2.40.3. These updates are from bugfixes in MAPL (and cmake) for the use of the NAG compiler.
All testing shows it to be zero-diff with Intel and GNU to ESMA_cmake v3.31.0 and MAPL 2.40.0.
=> Update to ESMA_cmake v3.31.1, MAPL 2.40.3

README.md, components.yaml
This PR updates to GEOSradiation_GridComp v1.5.1 which has a bugfix for the user-selectable RRTMGP T_MIN_OK parameter. This is zero-diff if you aren't using RRTMGP (and zero-diff if you are and don't change it).
=> Update to GEOSradiation_GridComp v1.5.1

README.md, components.yaml
This PR updates to Icepack geos/v0.0.3 which has a bug fix. This is trivially zero-diff (it only affects coupled runs with CICE6).
=> update Icepack to geos/v0.0.3 with a bug fix

.circleci/config.yml
Very boring PR. Updates the CI to use BCs v11.2.0.
=> Update to BCs 11.2.0

components.yaml
This PR adds `ignore_submodules: true` for CICE in GEOSgcm. This enables a new feature of mepo which should prevent `mepo status` from showing:
```
cice6                  | (t) geos/v0.0.2 (DH)
| icepack: modified, not staged
```
as well as `mepo diff` from showing a difference as well. We see this because *git* sees it since `git status` and `git diff` know that `icepack` was/is a submodule of CICE but we are "ignoring" it and not using it...but git doesn't know that.
So with this change, we can register with mepo that cice should run `status` and `diff` ignoring submodule changes.
I'll keep draft for now until I can test and ideally @zhaobin74 can test (since I really don't want to mess up his code). I think it's all good in my testing.
Note if you build locally, you want to get mepo …
=> Add ignore_submodules to cice

README.md, components.yaml
This PR updates to Icepack geos/v0.1.0 which enabled a new feature: mushy layer thermodynamic scheme. This is trivially zero-diff (it only affects coupled runs with CICE6).
=> update Icepack to geos/v0.1.0 with a new feature (mushy layer)

README.md, components.yaml
This PR updates GEOSgcm to use MAPL 2.41.0 and ESMA_cmake v3.34.0. 
The [changes in MAPL 2.41.0 are manyfold](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.41.0), but all testing shows this is zero diff.
The ESMA_cmake changes are mainly support for Rosetta as well as updates to NAG flags.
=> Update to MAPL 2.41.0 and ESMA_cmake v3.34.0

README.md, components.yaml
This PR updates to CICE6 geos/v0.1.0 which enabled a new feature: C-EVP dynamic scheme. This is trivially zero-diff (it only affects coupled runs with CICE6).
Depends on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/824
=> update CICE6 to geos/v0.1.0 with new C-EVP feature

README.md, components.yaml
This PR is gathering all the zero-diff updates from the latest HWT experiments.
Updates:
* GEOSgcm_App v2.2.2 → v2.2.3
* FVdycoreCubed_GridComp v2.6.0 → v2.7.0
* GFDL_atmos_cubed_sphere geos/v2.4.1 → geos/v2.5.0
* GMAO_Shared v1.9.2 → v1.9.4
NOTE: GEOSgcm_GridComp update went in with #658 as that PR required both CICE and GEOSgcm_GridComp be taken at the same time.
=> Updates from HWT experiments (zero-diff)

CHANGELOG.md, CMakeLists.txt, README.md, components.yaml
This PR has non-zero-diff updates from HWT experiments:
- GEOSgcm_GridComp v2.2.1 → v2.3.0
- GFDL_atmos_cubed_sphere geos/v2.5.0 → geos/v2.6.0
=> Updates from HWT Experiments (Non-zero-diff)

README.md, components.yaml
This PR updates icepack to geos/v0.1.1. This was a patch fixing a bug causing the crash in 1440x1080 configuration. See https://github.com/GEOS-ESM/Icepack/pull/3 for details. This is trivially zero-diff (it only affects coupled runs with CICE6).
=> update icepack to geos/v0.1.1 with a patch

README.md, components.yaml
This updates ESMA_env to v4.20.3 which has fixes for using `parallel_build.csh` with the Milans at NCCS. Namely, if you build on Milan, by default you will get `build-SLES15` and `install-SLES15` directories now, and `-SLES12` appended on everything else.
=> Update to ESMA_env v4.20.3

README.md, components.yaml
This PR updates GEOSgcm to use ESMA_env v4.20.4 which has fixes for `parallel_build.csh`. Essentially, this version actually doesn't break when you use other options.
=> Update to ESMA_env v4.20.4

README.md, components.yaml
This PR updates to ESMA_cmake v3.36.0. This has fixes for building on macOS under Rosetta with Intel as well as a fix for building with `icx`.
Neither of these are used by the usual ways of building GEOS but rather in ongoing development testing.
=> Update to ESMA_cmake v3.36.0

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.42.0. This has many new features and fixes but the main one is it fixes the `WRITE_RESTART_BY_OSERVER` issue @sdrabenh discovered.
All my tests show it zero-diff
=> Update to MAPL 2.42.0

README.md, components.yaml
This update to ESMA_env fixes the clean option for `parallel_build.csh`. Before this it would just always clean it.
=> Update to ESMA_env v4.20.6

README.md, components.yaml
This PR updates GEOS to use [fvdycore geos/v2.7.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.7.0). This is zero-diff for GEOSgcm as it adds support for a by-default-off new way of computing coordinates.
This is a companion PR to https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/258 and https://github.com/GEOS-ESM/GEOSgcm_App/pull/535. Both of these use the new namelist parameter added in fvdycore geos/v2.7.0. But we can't add that flag until we have the Fortran to support it.
Thus, we get this in first, then we can dribble in the other two PRs.
=> Update to fvdycore geos/v2.7.0

.circleci/config.yml
An upcoming PR from @sanAkel (see https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/47) will need an update to CI BCs. This is trying to preempt that issue here.
=> Update CI BCs to v11.3.0

README.md, components.yaml
This updates GEOS to the latest NCEP_Shared. This is trivially zero-diff as NCEP_Shared v1.3.0 only changed NCEP_crtm and the GEOSgcm sparses out that directory.
=> Update to NCEP_Shared v1.3.0

README.md, components.yaml
Update to FVdycoreCubed_GridComp v2.9.0 which simply adds a line to a namelist heredoc in `fv3.j`.
Note that this *REQUIRES* [GFDL_atmos_cubed_sphere geos/v2.7.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.7.0) but that is in `main` now (see #696)
=> Update to FVdycoreCubed_GridComp v2.9.0

README.md, components.yaml
This PR updates to CICE6 geos/v0.1.3 which adds support for running CICE6 in replay mode. This is trivially zero-diff (it only affects coupled runs with CICE6).
=> update cice6 to geos/v0.1.3

README.md, components.yaml
This PR moves GEOSgcm to use ESMA_env v4.22.0 aka Baselibs 7.15.1. 
~It also moves GEOS to use Open MPI 5.0.0 on SLES15 at NCCS.~ Due to https://github.com/open-mpi/ompi/issues/12113, we revert back to Open MPI 4.1.5 which is in v4.22.0
All my tests show this to be zero-diff, but @sdrabenh will check as well.
=> Update to Baselibs 7.15.1

README.md, components.yaml
Closes #654 
This PR updates fvdycore to geos/v2.8.0. This has a fix from @aoloso for the layout non-reproducibility at C180+. Huzzah!
All tests show at low-res it is zero-diff.
=> Update to fvdycore geos/v2.8.0

.circleci/config.yml
This PR updates the CircleCI here to use the new v2 orb. The main change is the need to use snake_case for everything.
=> Update to circleci-tools v2 orb

README.md, components.yaml
This PR updates GEOS to use fvdycore 2.8.1. This update has a fix by @atrayano when using the non-default locally generated coordinate path.
This is zero-diff for the usual way of running GEOS.
=> Update to fvdycore 2.8.1

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
Upcoming changes in MAPL will need ESMF 8.6.0. As such, we update ESMA_env (aka Baselibs) to get ESMF 8.6.0. This actually came in 7.16.0, but this also moves us up to get an update set of GFE libraries needed for upcoming MAPL3 development as well.
=> Update to Baselibs v7.17.0

.circleci/config.yml, README.md, components.yaml
This updates GEOSgcm to use MAPL 2.43.0. This has NAG fixes (in the 2.42 series) and MAPL 2.43 has some new features and bug fixes on top of 2.42 (see https://github.com/GEOS-ESM/MAPL/releases/tag/v2.43.0)
=> Update to MAPL 2.43.0

README.md, components.yaml
This PR updates to GEOSradiation_GridComp v1.6.0. This release of GEOSradiation_GridComp has a few updates (see https://github.com/GEOS-ESM/GEOSradiation_GridComp/pull/27):
1. The Load Balancing code in Solar was reworked to not call MAPL_LoadBalance code when not load balancing. Previously, it used a naive approach which still did MPI calls for no reason. Now it avoids that.
2. Adds the ability to change the `MaxPasses` parameter when loadbalancing via the `SOLAR_LB_MAX_PASSES:` AGCM.rc resource. By default it uses 100 which is the default in MAPL
3. Fixes for the profilers. Testing by @wmputman and @atrayano at high-res found that some columns over an integration period might not have, say, any clouds. This would then avoid some code in RRTMG which meant some timers were not turned …
=> Update to GEOSradiation_GridComp v1.6.0

README.md, components.yaml
This PR updates GEOSgcm to use ESMA_cmake 3.40. This adds support for an `ESMF::ESMF` target alias in CMake using Baselibs builds. This is needed due to an issue encountered by our UFS colleagues (see https://github.com/GEOS-ESM/MAPL/issues/2569).
Once this PR is in, a change will be made in MAPL proper and released as MAPL 2.44 which will require this version. But we get it in now so that the MAPL CI will work. 
Built and tested on Discover and zero-diff. As expected as the only effect of this is: build or not build.
=> Update to ESMA_cmake v3.40.0

.gitignore, CMakePresets.json, presets/CMakeDefaultPresets.json, presets/CMakeNCCSPresets.json
This is an attempt to change the build pattern using `CMakePresets.json` to work smarter at NCCS. If this works, let say you have a checkout of GEOSgcm in:
```
/discover/swdev/mathomp4/Models/GEOSgcm-FixPresets
```
along with the following environment variables (with examples for me):
```
CMAKE_PRESET_NAME=NCCS
CMAKE_BUILD_LOCATION=/discover/nobackup/projects/gmao/SIteam/mathomp4/cmake-builds
CMAKE_INSTALL_LOCATION=/discover/nobackup/projects/gmao/SIteam/mathomp4/cmake-installs
```
Then when you do:
```
cmake --preset Debug && cmake --build --preset Debug -j 10
```
it will put the build dir in:
```
/discover/nobackup/projects/gmao/SIteam/mathomp4/cmake-installs/GEOSgcm-FixPresets/build-Debug
```
and installs to:
```
/discover/nobackup/projects/gmao/SIteam/mathomp4/cmake-installs/GEOSgcm-Fi …
```
=> Add Special NCCS Build Preset

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.44.0. This requires updated ESMA_env and ESMA_cmake, but both versions are already in GEOSgcm `main`:
- ESMA_env v4.25.0 → #730 
- ESMA_cmake v3.40.0 → #746 
The [changes in MAPL 2.44](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.44.0) are manyfold, but it is zero-diff. Indeed, one change (from MAPL 2.43.2) is a fix for a memory leak!
=> Update to MAPL 2.44.0

README.md, components.yaml
This PR updates icepack to geos/v0.2.0. This update includes code to enable delta Eddington shortwave scheme.  This is trivially zero-diff (it only affects coupled runs with CICE6).
=> update Icepack to turn on dEdd shortwave scheme

README.md, components.yaml
This PR updates ESMA_cmake to [v3.41.0](https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.41.0). The main purpose for this is to set the MPI Stack by CMake rather than by looking at `$BASEDIR` which will not be feasible for Spack use.
This is a prerequisite for an other PR upcoming in GEOSgcm_App but which can't work without this PR.
=> Update to ESMA_cmake v3.41.0

README.md, components.yaml
This PR update GEOSgcm to use FVdycoreCubed_GridComp. The [main change](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/compare/v2.10.0...v2.11.0) is changing `fv3_setup` to use CMake rather than `$BASEDIR` to detect MPI stack (cf https://github.com/GEOS-ESM/GEOSgcm_App/pull/580)
There is also some CI stuff that doesn't matter. 😄
=> Update to FVdycoreCubed_GridComp v2.11.0

README.md, components.yaml
This is a meta-PR for updating the components in GEOSgcm to use RRTMGP v1.7 which requires an updated GEOSradiation_GridComp as well:
- [RRTMGP v1.7](https://github.com/GEOS-ESM/rte-rrtmgp/releases/tag/geos%2Fv1.7%2B1.0.0)
- [GEOSradiation_GridComp v1.8.0](https://github.com/GEOS-ESM/GEOSradiation_GridComp/releases/tag/v1.8.0)
To *run* RRTMGP v1.7 you also need a change in GEOSgcm_App currently in a PR: https://github.com/GEOS-ESM/GEOSgcm_App/pull/585
This is zero-diff for RRTMG runs, only changes RRTMGP runs.
Note also that RRTMGP v1.7 can be run in Single Precision mode with the CMake option:
```
-DRRTMGP_SINGLE_PRECISION=ON
```
Tests show that single-precision RRTMGP is about [10-20% faster than DP](https://github.com/GEOS-ESM/GEOSradiation_GridComp/pull/36#issuecomment-1971606964). …
=> Update to RRTMGP v1.7, GEOSradiation_GridComp v1.8.0

CMakeLists.txt
Testing by @sanAkel found an issue with building GEOS with spack as libraries. This fixes that issue.
Trivially zero-diff as CMake works or won't.
=> Fix up MPI detection for Spack builds

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.44.2. 
MAPL 2.44.1 is a patch on MAPL 2.44.0 which fixes a bug when users have instantaneous, bit-shaved binary HISTORY output that isn't purely diagnostic. In this case, it is non-zero-diff, but we know of no users of GEOSgcm using binary history output, so I'm listing as zero-diff. 
MAPL 2.44.2 has a bug fix for `time_ave_util.x` for when the input files have a level size of 1. This is trivially zero-diff until https://github.com/GEOS-ESM/GEOS_Util/pull/29 can be tested and merged in by @sdrabenh or @Jcampbell-8 or someone. But at least we know `time_ave_util.x` works better now!
=> Update to MAPL 2.44.2

README.md, components.yaml
This PR updates the SLES15 detection such that if the model is not built on SLES15, then the `BUILT_ON_SLES15` CMake variable will now be `FALSE` instead of a blank string.
This PR also then updates to GEOS_Util v2.0.8 which has a fix for `remap_restarts.py` to work with the new `BUILT_ON_SLES15` being `FALSE`.
NOTE: The other updates from ESMA_cmake v3.41 to v3.44 are for MAPL only (NAG flags and changes to tests).
=> Update to ESMA_cmake v3.44.0 and GEOS_Util v2.0.8

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This PR updates GEOSgcm to use Baselibs 7.23.0. The main change here is support for GCC 13. 
All testing shows zero-diff for Intel 2021.6, but non-zero-diff for GCC 12 → 13
=> Update to Baselibs 7.23.0

README.md, components.yaml
This PR is an omnibus PR that updates four repos. This PR has two functions:
1. GEOS runs on macOS with GCC 13.
2. GEOS runs on Linux with GCC 13 (when Baselibs 7.24.0 comes in in #750)
All my testing shows this is zero-diff for GEOSgcm with Intel and GCC.
---
This PR updates GEOS to use:
- [MAPL 2.45.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.45.0)
- This update had a [*lot* of changes](https://github.com/GEOS-ESM/MAPL/compare/v2.44.3...v2.45.0), but all testing shows it's zero-diff. 
- [ESMA_cmake v3.45.0](https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.45.0)
- Update to FindESMF.cmake to use ESMF::ESMF as the primary target and make ESMF an alias for ESMF::ESMF if it doesn't exist
- Updates for building with Clang on macOS
- Fixes for using f2py with Python 3.12
- …
=> Update to MAPL 2.45.0, ESMA_cmake v3.45.0, FV3 2.11.1, fvdycore geos/v2.8.2

README.md, components.yaml
This PR updates GEOSgcm to use:
* [FMS geos/2019.01.02+noaff.10](https://github.com/GEOS-ESM/FMS/releases/tag/geos%2F2019.01.02%2Bnoaff.10)
* [fvdycore geos/v2.9.0](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/releases/tag/geos%2Fv2.9.0)
* GOCART sdr_v2.2.1.2
The FMS and FV updates are from @climbfuji and @cmgas who are working with @rtodling on getting GEOS and JEDI to work happily with each other. These updates provide the feature to point FMS/FV to a non-standard `input.nml` location. (@climbfuji can say more if I have that wrong).
The GOCART update is needed because, as found by @climbfuji, if you build GEOSgcm, you get three sets of CMake files for doing `find_package`: MAPL, GEOSgcm, and GOCART. This then causes circular dependencies as GOCART requires things "provided" by …
=> Updates for GEOS-JEDI Work

README.md, components.yaml
As found by @climbfuji, there was a bug in the CMake for macOS on machines with older XCode. I'd hardcoded in "use ld_classic" but that's not needed on all macs.
This update fixes that.
=> Update to ESMA_cmake v3.45.2

components.yaml
I noticed that the `feature/sdrabenh/gcm_v12-rc1` branch is now pointing to a branch of radiation that might be deleted at some point. So we instead point it to `feature/sdrabenh/gcm_v12-rc1` until a tag is made.
=> Update Radiation GC to more stable branch

README.md, components.yaml
This PR updates ESMA_cmake to [v3.46.0](https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.46.0). This release adds a new cmake function that is currently being used in MAPL3 development. But we might as well get it in here so we don't lose it.
=> Update ESMA_cmake to v3.46.0

README.md, components.yaml
This updates GEOSgcm to [MAPL 2.47.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.47.0). All testing shows this is zero-diff to MAPL 2.46. 
Probably the main updates to 2.47.0 are:
- Updates to the station sampler code by @metdyn to make it faster
- Added capability to mangle `LONG_NAME` in ACG with a different prefix by @darianboggs 
The latter was requested by @acollow for work in M21C (see #792) and FP and elsewhere. To use it will require a change to GOCART a la https://github.com/GEOS-ESM/GOCART/pull/278. Of course, for current GEOSgcm, this will need to be done relative our GOCART sdr_v2.2.1.2 (aka a new sdr_v2.2.1.3 I suppose).
=> Update to MAPL 2.47.0

README.md, components.yaml
This PR is zero-diff for the default configurations.
It is non-zero-diff for TR tracers Be7, Be10 and Pb210.
And bug fixes / improvements to GMI and CARMA make it non-zero-diff when those modules are run.
Details:
In CARMA: Fixed the radiation callback, and the sulfate production tendency
In GMI: bug fix for emissions and deposition (related to SZA); better convergence in solver; reduction of HCl anomalies; default settings now mirror those from Benchmark G.
In TR: Changed the defaults regarding convection, settling, dry deposition and wet removal, for species Be7, Be10 and Pb210.
=> Uptick CHEM, GMI and TR (summer 2024)

.circleci/config.yml, .github/workflows/workflow.yml
This PR updates the CI to 7.25.0. Mainly for MAPL3 work, but we move regardless
=> Update CI Baselibs to 7.25.0

components.yaml
This PR updates R21C to use MAPL v2.35.3+R21C_v1.2.0. This tag of MAPL has the ACG fixes needed by @acollow to clean up the long name handling in GOCART (see https://github.com/GEOS-ESM/GOCART/pull/278).
Note that this is required for https://github.com/GEOS-ESM/GOCART/pull/278 since it adds an option to the ACG that PR needs.
=> Update R21C to MAPL v2.35.3+R21C_v1.2.0

README.md, components.yaml
@bena-nasa found a bug in MAPL 2.47.0 in FieldSet routines when passing R8 ESMF fields. 
Always good to fix bugs.
=> Update to MAPL 2.47.1

README.md, components.yaml
This updates ESMA_cmake to v3.48.0. This has a change in MPI detection useful for Spack work.
=> Update to ESMA_cmake v3.48.0

.circleci/config.yml, .github/workflows/workflow.yml, CMakeLists.txt, README.md, components.yaml, src/Shared/CMakeLists.txt
As we move to FMS in Baselibs, we shouldn't use the old `fms_r4` and `fms_r8` targets
anymore as they are non-standard. Instead we move to `FMS::fms_r4` and `FMS::fms_r8`.
This also adds a preliminary shot at supporting FMS with YAML support, although this has not been tested.
We also update to ESMA_cmake v4.5.0 to bring in a new cmake function (needed for MAPL 3), a fix for Spack work, and a NAG workaround.
We also update to ESMA_env v5.3.0 which brings in Baselibs 8.5.0 and Intel ifort 2021.13
We also update to MOM6 geos/v3.2 and Ocean GC v3.3.0. 
NOTE NOTE NOTE: The ESMA_env update is zero-diff for the *state* but non-zero-diff for *history*. Not sure why, but I have confirmed it's due to the compiler update. But this update is needed.
=> v12: Update FMS CMake target, Baselibs 8.5.0, and more

README.md, components.yaml
This PR updates to ESMA_cmake v3.51.0.
This has an update needed for MAPL3 development as well as NAG fixes and is inconsequential to the GCM. But we might as well get it in!
It also has support for Jemalloc and LLVM Flang.
=> Update to ESMA_cmake v3.51.0

README.md, components.yaml
This PR updates GEOS to [MOM6 geos/v3.2](https://github.com/GEOS-ESM/MOM6/releases/tag/geos%2Fv3.2) and [Ocean GC v2.3.0](https://github.com/GEOS-ESM/GEOS_OceanGridComp/releases/tag/v2.3.0). This is zero-diff for MOM6 runs due to setting non-default settings in `MOM_override` (see release notes).
ETA: Updated to [MOM6 geos/v3.3](https://github.com/GEOS-ESM/MOM6/releases/tag/geos%2Fv3.3) which is zero-diff to geos/v3.2 with our flags. (The new changes are from https://github.com/mom-ocean/MOM6/pull/1634 which deal with FMAs and our flags don't seem to care.)
=> Update to MOM6 geos/v3.3 and Ocean GC v2.3.0

README.md, components.yaml
This PR updates GEOSradiation_GridComp to v1.9.0. This release has a bugfix to Solar that is zero-diff to the state. If a user somehow requested certain exports, it's possible the history output could be non-zero-diff, but the trigger for the bug was causing 0/0 NaNs.
It also has minor CMake changes and adds in some preprocessing scripts.
=> Update to GEOSradiation_GridComp v1.9.0

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This PR updates v12 to ESMA_cmake v4.6.0. This has preliminary support for Jemalloc and LLVM Flang.
It also updates to ESMA_env v5.4.1 which has updates for NAS as well as moving the default build processor for `parallel_build.csh` to Milan at NCCS and Rome at NAS.
=> Update to ESMA_cmake v4.6.0, ESMA_env v5.4.1

README.md, components.yaml
This PR updates GEOSgcm to MAPL 2.48.0. Testing shows this is zero-diff to MAPL 2.47.
The [changes in MAPL 2.48.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.48.0) are a lot, but most of them don't really affect standard runs of GEOSgcm. You have to enable non-standard features and even then the changes would be in metadata of history.
=> Update to MAPL 2.48.0

README.md, components.yaml
Update to v1.9.9 which has a bug fix for GCC 14 (and clang per @gmao-ckung) as well as other minor fixes (see https://github.com/GEOS-ESM/GMAO_Shared/releases/tag/v1.9.9)
As found by @tclune and @gmao-ckung, XCode 16 on macOS has caused an issue where the `-pipe` GNU compiler flag causes errors in CMake builds.
It doesn't seem to be crucial and research online says the pipe flag isn't really that crucial for fast builds anymore.
=> Update to GMAO_Shared v1.9.9, ecbuild geos/v1.4.0

README.md, components.yaml
This PR updates the GCM to use MAPL 2.49.1.
The changes are actually pretty minor for how we run GEOS. MAPL 2.49.0 added zstandard compression support, but only Spack builds of MAPL/GEOS can utilize that at present.
MAPL 2.49.1 has a bug fix for an issue our UFS colleagues found, but as far as I know, we (GMAO) have never hit it.
=> Update to MAPL 2.49.1

CMakeLists.txt, README.md, components.yaml, src/Shared/CMakeLists.txt
This PR allows Spack to build GEOS using MAPL as an external dependency rather than internal.
=> Add ability to use MAPL as a library

CMakeLists.txt, README.md, components.yaml
MAPL 2.50.0 has a bugfix when using point source emissions with stretched grids. All testing shows it zero-diff to MAPL 2.49
MAPL 2.50.1 has a bugfix that was causing issues with GNU + Debug and ExtData2G
=> v11: Update to MAPL 2.50.1

README.md, components.yaml
This updates ESMA_env to v4.29.1 which moves to Intel MPI 2021.13 at NCCS on SLES15.
This should be taken in concert with https://github.com/GEOS-ESM/GEOSgcm_App/pull/652
This is tested zero-diff to Open MPI.
=> v11: Update to Intel MPI 2021.13

.github/workflows/release-tarball.yml, CMakeLists.txt, README.md, components.yaml, src/Shared/CMakeLists.txt
This PR adds the ability for Spack to build GEOSgcm as using MAPL as an external rather than internal dependency.
=> v12: Add ability to use MAPL as a library

README.md, components.yaml
This PR updates fvdycore to geos/v2.9.1 which has a bug fix for running with GCC 14 in Debug mode.
All tests show it is zero-diff for Intel runs.
=> Update to fvdycore geos/v2.9.1

.circleci/config.yml, .github/workflows/workflow.yml
This PR updates the CI to use GCC 14 for its GNU testing. This matches what we run in nightly tests.
=> v11: Update CI to use GCC 14

.circleci/config.yml, README.md, components.yaml
This PR updates to GEOSradiation_GridComp v1.10.0. This version has a fix for running with the Intel `ifx` compiler.
All testing shows it is zero diff for the old `ifort` compiler.
=> Update to GEOSradiation_GridComp v1.10.0

.circleci/config.yml, .github/workflows/workflow.yml, CMakeLists.txt, README.md, components.yaml, parallel_build.csh
This PR update GEOSgcm v12 to use ESMA_env v5.5.1. This has an update to Baselibs 8.7.0 which has ESMF 8.7.0. The main benefit to this is lower memory cost at very-high core count (thanks to @tclune and @atrayano for finding this!).
We also move to ESMA_cmake v4.9.0 which adds support for Python 3.12 as well as code to run `mepo status` at CMake time and capture that output for experiments.
All testing shows it zero-diff to v5.4.1
NOTE: 5.5.1 re-sets the executable bit on g5_modules. Not sure why it was removed.
=> v12: Update to Baselibs 8.7.0

.circleci/config.yml, .github/workflows/workflow.yml
This PR updates v11 CI to use Ubuntu 24 in CI and Docker.
=> v11: Move to use Ubuntu 24 in CI and Docker

README.md, components.yaml
This PR updates GEOSgcm to use MAPL v2.51.2. This has bug fixes for issues @zhaobin74 found:
1. Using multiple rules with vectors was broken
2. Relaxes the restriction that vector regridding can only be bilinear
All my testing shows this to be zero-diff to MAPL v2.51.1
=> v11: Update to MAPL v2.51.2

README.md, components.yaml
This PR updates ESMA_cmake to use the `LOCATION` strategy for finding Python. This is needed as NAS (at least) has a very recent, but empty (no f2py) Python stack in the default path. Using `LOCATION` should limit it to the Python we want (e.g., via GEOSpyD module)
---
We also update to ESMA_env v4.29.2. This change updates g5_modules to use an MPT 2.30 Baselibs at NAS. This is due to NAS updating the `mpi-hpe/mpt` module to `mpi-hpe/mpt.2.30`. While this does not break GEOS, CMake throws more errors due to differences in MPT that built Baselibs vs MPT that would build GEOS.
It also moves up to Baselibs 7.27.0 which has the latest libraries.
---
We also update to FV3 GC v2.13.0. This release adds a dependency to `fms_r4`. We need this because of the weird way we build FV3 as r4 but link …
=> v11: Update to ESMA_cmake v3.56.0, FV3 GC v2.13.0, ESMA_env v4.29.2

CMakeLists.txt, README.md, components.yaml
This PR updates to MAPL 2.52.0. 
This release has new features and a few fixes (including an issue found by @atrayano where running replay for a long time with replay and Intel MPI can cause MPI to exhaust communicators).
All testing show it zero-diff to MAPL 2.51
=> v11: Update to MAPL 2.52.0

README.md, components.yaml
This PR updates v11 to [HEMCO `geos/v2.3.0`](https://github.com/GEOS-ESM/HEMCO/releases/tag/geos%2Fv2.3.0). This has a fix for an issue noticed by @sdrabenh where GEOSgcm would not layout regress if `hemco_internal_rst` was present.
NOTE: This is non-zero-diff to HEMCO `geos/v2.2.3`.
=> v11: Update to HEMCO geos/v2.3.0

.circleci/config.yml, .github/workflows/workflow.yml, CMakeLists.txt, README.md, components.yaml
This PR updates ESMA_cmake to use the `LOCATION` strategy for finding Python. This is needed as NAS (at least) has a very recent, but empty (no f2py) Python stack in the default path. Using `LOCATION` should limit it to the Python we want (e.g., via GEOSpyD module). 
We also update ESMA_cmake to change the Intel Fortran flags to new ones by @wmputman. 
_**NOTE: This is NON-ZERO-DIFF!**_
We also update to ESMA_env v5.7.0 which moves to use MPT 2.30 Baselibs at NAS and to Baselibs 8.9.0 (which has ESMF 8.8.0)
I've also updated CI to use Ubuntu 24 and modernized the CMake calls in `README.md`
=> v12: Update to ESMA_cmake v4.12.0, ESMA_env 5.7.1

CMakeLists.txt, README.md, components.yaml
This PR updates to MAPL 2.54.0. 
The changes in MAPL 2.53.0 didn't really apply to GEOS runs (was for UFS) but 2.53.1 fixes a case where those changes did cause issues with GEOS.
MAPL 2.54 adds a new feature in the ACG needed for work in GWD by @pchakraborty (see https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/1053).
All testing shows this to be zero-diff for GEOSgcm.
=> v11: Update to MAPL 2.54.1

README.md, components.yaml
This PR updates GEOSgcm to use ESMA_env v4.35.0 → Baselibs 7.32.0.
The difference is an update to GFE v1.19.0 which brings in gFTL v1.15 which is needed for MAPL3 development.
All my testing shows it as zero-diff.
=> v11: Update to Baselibs 7.32.0

README.md, components.yaml
This PR updates GEOSradiation_GridComp to v1.11.0. This release has fixes for the `ifx` compiler in the Irrad GC. v1.10.0 had the fixes in Solar, but it turned out that wasn't enough.
All testing with GEOS shows it to be zero-diff.
NOTE: #884 updates to Radiation v1.12.0 for RRG support. So if that goes in before this, this can be closed.
=> v11: Update to GEOSradiation_GridComp v1.11.0

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This PR updates v12 to [HEMCO `geos/v2.3.0`](https://github.com/GEOS-ESM/HEMCO/releases/tag/geos%2Fv2.3.0). This has a fix for an issue noticed by @sdrabenh where GEOSgcm would not layout regress if `hemco_internal_rst` was present.
NOTE: This is non-zero-diff to HEMCO `geos/v2.2.3`.
=> v12: Update README for HEMCO geos/v2.3.0

.circleci/config.yml, .github/workflows/workflow.yml, README.md, components.yaml
This is a combo PR of #827 and #877 to see if we can just do the all at once. This way @mmanyin needs only one new Chem GC release and @msl3v can get his RRG code in.
---
This PR moves MAM, MATRIX, CARMA, GAAS, and GEOSachem to separate repos. It also adds RRG. There will be a few steps to get this in:
=> Move MAM, MATRIX, CARMA, GAAS, ACHEM to separate repos; add RRG

README.md, components.yaml
This PR updates GEOSgcm v11 to GEOS_OceanGridComp v2.4.1. 
This has a bugfix from @zhaobin74 for an [issue with `FRZMLT`](https://github.com/GEOS-ESM/GEOS_OceanGridComp/issues/85). 
This is zero-diff for data-ocean runs, but non-zero-diff for MOM6 runs.
=> v11: Update to GEOS_OceanGridComp v2.4.1

.circleci/config.yml, README.md, components.yaml
This PR brings moves GMAO_perllib into its own repo.
Requires a new GMAO_Shared, see: https://github.com/GEOS-ESM/GMAO_Shared/pull/361
=> Remove GMAO_perllib into its own repo

README.md, components.yaml
This PR updates GEOSgcm v12 to GEOS_OceanGridComp to v2.5.0 and mom6 to geos/v3.5. These updates are from @mfmehari and have changes needed for NOBM work.
My testing shows it is zero-diff for both AMIP and MOM6 runs.
We also move the mepo `develop:` for mom6 to `geos/main`. That way `mepo develop mom6` points to the right branch (since we now have code outside of mom6 mainline).
=> v12: Update to Ocean GC v3.5.0, mom6 geos/v3.5

README.md, components.yaml
Added the mepo component [geos_state_bias](https://github.com/GEOS-ESM/geos_state_bias) to `components.yaml` of GEOSgcm.
This PR is contingent on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/1077 being accepted
=> Add geos_state_bias

README.md, components.yaml
This PR has updates to remove the SLES12/SLES15 OS detection that was needed at NCCS. It consists of the following PRs/tags:
- ESMA_cmake [v4.14.1](https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v4.14.1)
---
The Below PRs have all been merged:
- ESMA_env [v5.10.0](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v5.10.0)
- GEOS_Util: https://github.com/GEOS-ESM/GEOS_Util/pull/129
- GEOSgcm_GridComp: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/1078
- FVdycoreCubed_GridComp: https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/pull/300
- GEOSgcm_App: https://github.com/GEOS-ESM/GEOSgcm_App/pull/709
=> v12: Remove NCCS OS detection

README.md, components.yaml, parallel_build.csh
This PR updates to ESMA_cmake v3.59.0 which has fixes for using GEOS at NAS (mainly with f2py).
Also, I noticed that we weren't doing a blobless clone in the v11 parallel_build. This adds that because blobless clone is better clone.
=> v11: Update to ESMA_cmake 3.59, add blobless clone to parallel_build

README.md, components.yaml
This PR updates v12 to use Baselibs 8.14.0 (ESMA_env v4.16.0).
This also updates ESMA_cmake to v4.16.0 which has fixes for f2py as well as a CMake fix for the update to ecbuild geos/v2.0.0
=> v12: Update to Baselibs 8.14.0, ESMA_cmake v4.16.0, ecbuild geos/v2

.circleci/config.yml, CMakeLists.txt, README.md, components.yaml
This PR is from a conversation with myself and Nicko Acks of NCCS. Namely, it would be nice to have a file that determines build information of a GEOS build.
This PR requires some updates to ESMA_env and ESMA_cmake.
* [ESMA_env v5.12.0](https://github.com/GEOS-ESM/ESMA_env/tree/v5.12.0)
* [ESMA_cmake v4.18.0](https://github.com/GEOS-ESM/ESMA_cmake/tree/v4.18.0)
This is some example output:
```
== Build Configuration ==
Build Type: Debug
== System ==
System Name: Linux
System Version: 5.14.21-150400.24.100-default
Host System: Linux-5.14.21-150400.24.100-default
Processor Description: 128 core AMD EPYC 7713 64-Core Processor
== CMake ==
CMake Version Used for Build: 4.0.1
CMake Required Version: 3.24
== Git ==
Git Version: 2.49.0
== Modules == …
```
=> v12: Add Build Info, Update ESMA_env, ESMA_cmake

README.md, components.yaml
This PR updates GEOSgcm v11 to ESMA_cmake v3.63.0. This is mainly needed for an upcoming Baselibs update (which moves to libaec).
Zero-diff
=> v11: Update to ESMA_cmake v3.63.0

CMakeLists.txt, README.md, components.yaml
This PR updates GEOSgcm v12 to MAPL 2.60.0. Note that this is labeled as both zero-diff and non-zero-diff. The reason is that with the update, the `ss_internal_checkpoint` will change as a field `DEEP_LAKES_MASK` will not be in the checkpoint. This is actually the correct behavior as MAPL 2.60 fixes a bug in the MAPL Automatic Code Generator (ACG) used by GOCART to create the Fortran code for the various imports/exports/internals.
This is the non-zero-diff part, but the model as a whole is zero-diff. The state and history output will be zero-diff. `DEEP_LAKES_MASK` is a `MAPL_RestartSkip` field in the SS Internal state and is recalculated at each time step.
For more information, see the release notes for [MAPL 2.60.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.60.0)
=> v12: Update to MAPL 2.60.0

README.md, components.yaml
This PR updates GEOSgcm v11 to MAPL 2.59.1. This patch update to MAPL 2.59 adds support for ESMF v9. While MAPL 2 and GEOSgcm do not need ESMF v9 at the moment, MAPL3 does. This PR allows our CI and Baselibs to move to ESMF v9 without causing issues.
This has been tested as zero-diff when GEOSgcm v11 is built with Baselibs 8.18 (ESMF 8.9.0) and Baselibs 8.19 (ESMF v9.0.0b03)
=> v11: Update to MAPL 2.59.1

README.md, components.yaml
This PR updates v12 to ESMA_cmake v4.25.0 (Support for ifx 2025.2; bug fix for `FPE1` use in v12; remove support for Python 2; updated `ifort` flags, add new `VectTrap` build type) and to ESMA_env v5.15.0 (Baselibs 8.19.0 → ESMF v9.0.0b03; add `-vecttrap` option to `build.csh`).
Note the changes in ESMA_cmake for `ifort` flags were tested with other non-zero-diff changes in v12. But it seems likely that just the flag changes alone could cause non-zero-diff. So we label as such.
=> v12: Update to ESMA_cmake v4.25.0, ESMA_env v5.15.0
