GEOS-ESM/GEOSgcm

README.md
Bad Matt didn't sanitize the README. This isn't ADAS
=> Update README to remove ADAS refs

CMakeLists.txt
=> Update CMakeLists.txt: This project is GEOSgcm

Externals.cfg, config/GMAO_Shared.sparse, config/NCEP_Shared.sparse
This adds two files for the sparsing of `NCEP_Shared` and `GMAO_Shared`
Seems to work. Yay me. 😄
=> Fixes #1. Enable sparse checkout of NCEP_Shared and GMAO_Shared

Externals.cfg
=> Update to ESMA_cmake 1.0.8

Externals.cfg
This moves `GEOSgcm` level to CVS tag `Jason-3_1`
=> Update to code from Jason-3_1.

.circleci/config.yml, README.md
This commit hardcodes Matt's fix of UMD_Etc (https://github.com/GEOS-ESM/UMD_Etc/issues/6) for a green build. Once that branch is merge into UMD_Etc's master, the hardcoded fix can be removed.
=> Fixes #33: Added config file for CircleCI

Externals.cfg
=> move GMAO_Shared to v1.0.4

Externals.cfg
Another file was missing for plots that is in Jason-3_2
=> uptick to 1.0.5

Develop.cfg, Externals.cfg
Couldn't build, now can build.
=> Fixes #49. Corrects GFIO build bug

Develop.cfg
Fixes and additions to `parallel_build.csh`. Should be easily 0-diff as there is no change to the script if you don’t pass in options
=> Update to ESMA_env 1.4.0

Develop.cfg
This adds a `FINDLOC()` detection capability for code being added by @smahanam. It is trivially 0-diff.
=> Update to ESMA_cmake 1.0.11

CHANGELOG.md, Externals.cfg, components.yaml
=> Uptick master to v10.8.0

CMakeLists.txt
We've been forgetting to update this number!
=> Update Project Version number

Develop.cfg, Externals.cfg, components.yaml
The hope is this will fix at least one issue @wmputman is seeing at high-resolution.
Tests by myself and @bena-nasa seem to show this is zero-diff at C48.
I'll put a blocking tag on this until @wmputman or @bena-nasa can do a big test.
=> Fixes #125. Move to MAPL v2.0.2

Develop.cfg, Externals.cfg, components.yaml
This adds the ability to use `parallel_build.csh` with Skylake at NCCS. This can't be done without a bit more work, but it can be done.
=> Update to ESMA_env v2.0.4

Develop.cfg, Externals.cfg, components.yaml
Most of these are updates to better support checkouts and builds on non-NASA systems.
Updates in GMAO_Shared are more extensive, see [release notes](https://github.com/GEOS-ESM/GMAO_Shared/releases/tag/v1.1.2)
=> Updates to externals/components

Develop.cfg, Externals.cfg, components.yaml
Just a small update that really doesn't affect much other than letting ecbuild mount in various ways in re the @-symbol
=> Update to ESMA_cmake v3.0.1

Develop.cfg, Externals.cfg, components.yaml
This is to help support JEDI compatibility (part one of many PRs)
=> Update ESMA_cmake and ecbuild

Develop.cfg, Externals.cfg, components.yaml, src/Shared/CMakeLists.txt
As per #158, @sanAkel has indicated we can remove GSW. This PR will do so. Testing shows zero-diff at C48 as I'm not using MOM6 (nor do I know how 😄 )
=> Fixes #158. Remove GSW from CMake/GEOSgcm

Develop.cfg, Externals.cfg, components.yaml
This updates GMAO_Shared to v1.1.6 which mainly fixes a GCC 10 `Release` build issue.
=> Update GMAO_Shared to v1.1.6

Develop.cfg, Externals.cfg, components.yaml
This adds support for detecting AWS
=> Update to ESMA_cmake v3.1.1

Develop.cfg, Externals.cfg, components.yaml
This is needed for using Ubuntu images in CircleCI
=> Update to ESMA_cmake v3.1.2

.codebuild/buildspec.yml, .github/CODEOWNERS, README.md
=> Add AWS CodeBuild file

README.md
This adds a table to the README for CI status
=> Update README.md with CI Table

Develop.cfg, Externals.cfg, components.yaml
This is a zero-diff update that changes one flag in the Intel Debug build.
=> Update to ESMA_cmake v3.1.4

Develop.cfg, Externals.cfg, components.yaml
Update to use ESMA_env v3.0.1 which lowers the make job number in parallel_build
=> Update to ESMA_env v3.0.1

Develop.cfg, Externals.cfg, components.yaml
This is a bug fix in MAPL. Per the release:
- Fix bug with using coarse grids in History and ExtData
=> Update MAPL to v2.3.3

.circleci/config.yml, .github/workflows/workflow.yml
=> Add Github CI

Develop.cfg, Externals.cfg, components.yaml
Update MAPL to v2.3.4 for bugfixes.
=> Update MAPL to v2.3.4

.circleci/config.yml
Testing out how to best handle CircleCI degredation.
=> Degrade CircleCI to medium

.circleci/config.yml, .github/workflows/workflow.yml
The CI in here is woefully old. I guess I missed it.
=> Update Baselibs in CI

components.yaml
This is a minor zero-diff update to GOCART that mainly just fixes the CI to actually work with the GEOSgcm as it is. You can see the changes here:
https://github.com/GEOS-ESM/GOCART/compare/v1.0.0...v1.0.1
=> Update to GOCART v1.0.1

.github/workflows/workflow.yml
This annoyed me on MAPL, so I'm fixing it here.
=> Don't run CI if a label changes

README.md
Sometimes people get weird errors cloning with git. Hopefully this helps.
=> Update README with more git clone info [skip ci]

CHANGELOG.md, CMakeLists.txt, README.md, components.yaml, parallel_build.csh
Also adds a table to the README.md with links.
=> Update parallel_build to use GMAO_Shared main if develop

README.md, components.yaml
This updates GMAO_Shared to v1.4.5
=> Update to GMAO_Shared v1.4.5

.circleci/config.yml, components.yaml
This PR adds a run of GEOS to the CI. Note this requires MAPL 2.8.0 (see #312) so it is contingent on that.
=> Add GCM run to CI

README.md, components.yaml
Closes #336 
This PR updates GMAO_Shared to v1.4.8 which fixes a runtime segfault with CICE4.
=> Update GMAO_Shared to v1.4.8

.circleci/config.yml
This PR updates the CircleCI in GEOSgcm to use the GEOS CircleCi orb to allow for cleaner, reusable code.
=> Update GEOSgcm Fixture to use CircleCI Orb

README.md, components.yaml
This PR updates MAPL to v2.19.1 which has a bugfix from @atrayano for an issue found by @sdrabenh
=> Update to MAPL 2.19.1

.circleci/config.yml
This PR updates the CircleCI to use the v1 orb and job syntax.
=> Update CI to use v1 orb and job

.circleci/config.yml
It's probably a good idea to run the GCM in CI here in the fixture. This enables it.
=> Enable GCM run in CI

README.md, components.yaml
=> Advance Chemistry to v1.11.0

README.md, components.yaml
This is a branch to track changes to components from GEOSadas work. I figured let's not lose these. I'll keep draft for now until @sdrabenh is ready.
=> Update GCM Components

README.md, components.yaml
My changes in GOCART sdr_v2.1.2.5 had a bug exposed by the Debug builds:
https://github.com/GEOS-ESM/GOCART/compare/sdr_v2.1.2.5...sdr_v2.1.2.6
I issued sdr_v2.1.2.6 and this PR ups the GOCART version to fix it.
=> Fix missing inquires in GOCART

CHANGELOG.md, README.md, components.yaml
This PR has updates to the physics and dynamics from HWT work. It is non-zero-diff to the previous RC release of GEOSgcm (and even `main` as of this point).
=> Updates from HWT Tuning and Tests

README.md, components.yaml
This is a tracking PR for upticking components for GEOSgcm
=> Update components - 2023-May-17

README.md, components.yaml
The 1209342034832948th time is the charm. I think I finally got `parallel_build.csh` to work. I think. Once @sdrabenh pulls this in, we'll see...
=> Update to ESMA_env v4.20.5

README.md, components.yaml
Update GMAO_Shared to v1.9.6 for a bug fix for a Perl module used by `regrid.pl`
=> Update to GMAO_Shared v1.9.6

README.md, components.yaml
Uptick:
- GEOS_OceanGridComp to v2.1.4
- MOM6 to v2.2.3
=> Update MOM and OceanGC

README.md, components.yaml
Uptick following:
- [MOM6](https://github.com/GEOS-ESM/MOM6/tree/geos/v3.1)
- [GEOS_OceanGridComp](https://github.com/GEOS-ESM/GEOS_OceanGridComp/releases/tag/v2.1.6)
=> Uptick ocean components

.github/workflows/release-tarball.yml
This PR fixes the release tarball script. Needs update do to changes in mepo.
=> Fix release tarball script

components.yaml
Updates for setting up a run with the latest geos-chem version
=> Updates for setting up a run with the latest geoschem version

README.md
This PR adds some advice to `README.md` for setting up blobless clones with mepo.
=> Add mepo blobless advice

.github/workflows/spack-ci.yml, .github/workflows/workflow.yml
=> v12: Fixes for CI
